/**
 * Phase 6 — Additional Content Seeding (Batch 3)
 *
 * Reaches 50+ questions per category for all categories.
 *
 * Usage: npx tsx scripts/seed-content-batch3.ts
 */

import mongoose from "mongoose";
import path from "path";
import fs from "fs";

function loadEnv() {
  const envPath = path.resolve(process.cwd(), ".env.local");
  const fallbackEnvPath = path.resolve(process.cwd(), ".env");
  let envFile = "";
  if (fs.existsSync(envPath)) { envFile = fs.readFileSync(envPath, "utf-8"); }
  else if (fs.existsSync(fallbackEnvPath)) { envFile = fs.readFileSync(fallbackEnvPath, "utf-8"); }
  else { console.warn("[Seed] Warning: No .env.local or .env file found."); return; }
  envFile.split("\n").forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return;
    const parts = trimmed.split("=");
    if (parts.length >= 2) { process.env[parts[0].trim()] = parts.slice(1).join("=").trim().replace(/^['"]|['"]$/g, ""); }
  });
}
loadEnv();

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) { console.error("❌ MONGODB_URI missing"); process.exit(1); }

const categorySchema = new mongoose.Schema({ name: String, slug: { type: String, unique: true }, type: String, description: String, icon: String, order: Number, questionCount: Number, isPublished: Boolean }, { timestamps: true });
const questionSchema = new mongoose.Schema({ category: { type: mongoose.Schema.Types.ObjectId, ref: "Category" }, slug: { type: String, unique: true }, question: String, answer: { short: String, detailed: String, example: String }, videos: [{ label: String, url: String, order: Number }], difficulty: String, frequencyRank: Number, tags: [String], isPremium: Boolean, isPublished: Boolean }, { timestamps: true });
const Category = mongoose.models.Category || mongoose.model("Category", categorySchema);
const Question = mongoose.models.Question || mongoose.model("Question", questionSchema);

interface Q { slug: string; question: string; short: string; detailed: string; example?: string; difficulty: "easy"|"medium"|"hard"; rank: number; tags: string[]; premium: boolean; }

function makeQ(catSlug: string, q: Q) {
  return { categorySlug: catSlug, slug: q.slug, question: q.question, answer: { short: q.short, detailed: q.detailed, example: q.example || "" }, difficulty: q.difficulty, frequencyRank: q.rank, tags: q.tags, isPremium: q.premium };
}

function batch3Questions() {
  const all: ReturnType<typeof makeQ>[] = [];

  // ─── Frontend Engineering (26 more) ───────────────────────────────────
  const fe: Q[] = [
    { slug: "css-variables", question: "Explain CSS custom properties (variables) vs preprocessor variables.", short: "CSS custom properties are dynamic, runtime-evaluable, inherit, and accessible in JS.", detailed: "<p><strong>CSS Variables (Custom Properties):</strong> Rendered in the browser. Dynamic, accessible via JS (<code>getPropertyValue</code>), inherit through the cascade, and support fallback values. Excellent for theming.</p><p><strong>Sass/Less Variables:</strong> Compiled compile-time. Static in the final CSS. No runtime modifications or inheritance.</p>", rank: 26, difficulty: "easy", tags: ["css", "variables", "theming"], premium: false },
    { slug: "javascript-typeof-instanceof", question: "Compare typeof and instanceof in JavaScript.", short: "typeof returns primitive type string; instanceof checks prototype chain inheritance.", detailed: "<p><strong>typeof:</strong> Unary operator returning string representation of primitive types (string, number, boolean, undefined, symbol, bigint) and 'object' (including null, arrays) or 'function'.</p><p><strong>instanceof:</strong> Binary operator checking if constructor's prototype is in the object's prototype chain. Best for custom classes and arrays.</p>", rank: 27, difficulty: "easy", tags: ["javascript", "types", "fundamentals"], premium: false },
    { slug: "react-memo-vs-usememo", question: "Compare React.memo and useMemo.", short: "React.memo wraps components to prevent re-renders; useMemo memoizes computed values inside render.", detailed: "<p><strong>React.memo:</strong> Higher-Order Component. Shallowly compares props to avoid re-rendering the wrapped component if props haven't changed.</p><p><strong>useMemo:</strong> Hook. Memoizes the result of an expensive calculation inside a component rendering lifecycle, re-running only when dependencies change.</p>", rank: 28, difficulty: "medium", tags: ["react", "optimization", "memoization"], premium: false },
    { slug: "css-layout-positioning", question: "Explain CSS positioning types (static, relative, absolute, fixed, sticky).", short: "Static: default; Relative: offset from normal; Absolute: offset from nearest positioned ancestor; Fixed: viewport offset; Sticky: scroll-toggle behavior.", detailed: "<p><strong>Static:</strong> Standard document flow.</p><p><strong>Relative:</strong> Positioned relative to itself, space reserved.</p><p><strong>Absolute:</strong> Positioned relative to nearest positioned ancestor, removed from flow.</p><p><strong>Fixed:</strong> Positioned relative to viewport, stays in place.</p><p><strong>Sticky:</strong> Hybird, toggles relative and fixed based on scroll offsets.</p>", rank: 29, difficulty: "easy", tags: ["css", "layout", "positioning"], premium: false },
    { slug: "js-strict-mode", question: "What does 'use strict' do in JavaScript?", short: "Enforces strict parsing and error handling, preventing silent errors and bad coding practices.", detailed: "<p>Strict mode enforces cleaner JS coding standards by: throwing errors on global variable leaks, disabling <code>with</code> statement, preventing duplicate property names, throwing errors on read-only updates, and keeping <code>this</code> undefined in global function calls.</p>", rank: 30, difficulty: "easy", tags: ["javascript", "strict-mode", "fundamentals"], premium: false },
    { slug: "dom-painting-layout-reflow", question: "Explain Layout, Paint, and Composite in browser rendering.", short: "Layout calculates element geometry; Paint fills in colors/details; Composite layers them together. Minimizing Layout/Paint optimizes speed.", detailed: "<p><strong>Layout (Reflow):</strong> Calculating sizes and positions of all elements. Triggered by geometry changes.</p><p><strong>Paint:</strong> Drawing pixels (colors, borders, text, shadows) on layers.</p><p><strong>Composite:</strong> Stacking layers on screen via GPU. Fast. Triggered by transform/opacity animations.</p>", rank: 31, difficulty: "hard", tags: ["browser", "performance", "rendering"], premium: true },
    { slug: "html-semantic-tags", question: "Why is semantic HTML important?", short: "Improves SEO, makes structure clearer, and provides native accessibility hooks for screen readers.", detailed: "<p>Semantic tags (&lt;main&gt;, &lt;article&gt;, &lt;nav&gt;, &lt;footer&gt;) convey meaning rather than visual presentation. They help search crawlers understand page layout and allow screen readers to parse navigation layouts automatically.</p>", rank: 32, difficulty: "easy", tags: ["html", "semantics", "accessibility"], premium: false },
    { slug: "react-context-perf-issues", question: "How do you avoid performance issues with React Context?", short: "Split Context, memoize values, or use state selectors (e.g. Zustand) to prevent broad child re-renders.", detailed: "<p>React Context triggers a re-render for ALL consumers when the context value changes. To mitigate: (1) Split state and dispatch into separate contexts, (2) Wrap children with memoization, (3) Use state management libraries that allow selectors.</p>", rank: 33, difficulty: "medium", tags: ["react", "context", "performance"], premium: false },
    { slug: "web-workers-vs-service-workers", question: "Compare Web Workers and Service Workers.", short: "Web Workers run parallel threads for heavy logic; Service Workers act as network proxies for offline support.", detailed: "<p><strong>Web Workers:</strong> General-purpose background threads. Communcate via postMessage. Used for complex computations to keep main thread free.</p><p><strong>Service Workers:</strong> Proxy servers between browser, network, and cache. Can intercept requests, support offline usage, push notifications, and sync in background.</p>", rank: 34, difficulty: "medium", tags: ["web-workers", "service-workers", "javascript"], premium: false },
    { slug: "js-microtasks-vs-macrotasks", question: "Explain JavaScript microtasks and macrotasks.", short: "Microtasks (Promises) execute immediately after the current script; macrotasks (setTimeout) execute on subsequent loop ticks.", detailed: "<p>The event loop executes tasks in order: (1) Run call stack functions, (2) Execute all microtasks in queue (Promise.then, MutationObserver), (3) Execute one macrotask from queue (setTimeout, setInterval, postMessage), (4) Re-render if needed.</p>", rank: 35, difficulty: "medium", tags: ["javascript", "event-loop", "asynchronous"], premium: false },
    { slug: "react-18-concurrent-features", question: "What is Concurrent Mode in React 18?", short: "Allows React to interrupt, pause, or discard renders to keep the main thread responsive during heavy updates.", detailed: "<p>Concurrent features like <code>useTransition</code> and <code>useDeferredValue</code> let developers mark renders as non-blocking transitions. React will yield to user inputs (clicks, keypresses) during the render.</p>", rank: 36, difficulty: "hard", tags: ["react", "concurrency", "performance"], premium: true },
    { slug: "web-analytics-tracking-layer", question: "How do you build a secure web analytics layer?", short: "Abstract page views and actions behind a unified custom events tracker to decouple GA4, Plausible, or PostHog.", detailed: "<p>Create an abstract wrapper with functions like <code>trackPageview</code> and <code>trackEvent</code>. This lets you swap metrics destinations without polluting components code, keeping dependencies clean.</p>", rank: 37, difficulty: "medium", tags: ["analytics", "architecture", "telemetry"], premium: false },
    { slug: "css-preprocessors-vs-tailwind", question: "Compare Tailwind CSS with Sass/SCSS preprocessors.", short: "Tailwind uses utility classes for inline layout; Sass uses precompiled nested rules and mixins.", detailed: "<p>Tailwind is utility-first, reducing final stylesheet size by recycling classes. CSS-in-JS and Sass can result in larger file weights but provide deep nesting structures.</p>", rank: 38, difficulty: "easy", tags: ["css", "tailwind", "sass"], premium: false },
    { slug: "javascript-modules-esm-cjs", question: "Compare CommonJS (CJS) and ES Modules (ESM).", short: "CJS uses require/module.exports (synchronous); ESM uses import/export (asynchronous, tree-shakeable).", detailed: "<p><strong>CommonJS:</strong> Node.js standard. Dynamic imports supported. Dynamic loading at runtime. Not tree-shakeable.</p><p><strong>ES Modules:</strong> Modern browser/node standard. Static imports allow build-time tree shaking and optimization.</p>", rank: 39, difficulty: "easy", tags: ["javascript", "modules", "esm", "cjs"], premium: false },
    { slug: "react-controlled-vs-uncontrolled", question: "Explain controlled vs uncontrolled components in React.", short: "Controlled uses React state to drive input values; uncontrolled uses ref to pull values from DOM.", detailed: "<p><strong>Controlled:</strong> Value matches state. Single source of truth. Best for validation. Re-renders on input.</p><p><strong>Uncontrolled:</strong> DOM manages values. Access via refs. Good for simple forms and file inputs.</p>", rank: 40, difficulty: "easy", tags: ["react", "forms", "refs"], premium: false },
    { slug: "web-storage-api", question: "Compare localStorage, sessionStorage, and cookies.", short: "LocalStorage persists indefinitely; SessionStorage cleared on tab close; Cookies sent with HTTP requests.", detailed: "<p><strong>localStorage:</strong> 5MB, client-only, survives page reload and window restarts.</p><p><strong>sessionStorage:</strong> 5MB, client-only, scoped to current browser tab.</p><p><strong>Cookies:</strong> 4KB, sent automatically to server on every request. Supports HttpOnly/Secure flags for safety.</p>", rank: 41, difficulty: "easy", tags: ["storage", "cookies", "security"], premium: false },
    { slug: "nextjs-middleware-use-cases", question: "What are common use cases for Next.js Middleware?", short: "Authentication verification, redirect routing, geo-targeting, rate limiting, and header manipulation.", detailed: "<p>Middleware runs before requests are completed. It allows modifying headers, validating session cookies, performing geo-blocking, or managing redirections globally.</p>", rank: 42, difficulty: "medium", tags: ["nextjs", "middleware", "routing"], premium: false },
    { slug: "react-custom-hooks", question: "Why would you write a custom React hook?", short: "To extract and share stateful logic across multiple components without duplicating code.", detailed: "<p>Custom hooks are functions starting with 'use' that call other hooks. They share logic (like fetching, subscriptions, timers) rather than state itself.</p>", rank: 43, difficulty: "easy", tags: ["react", "hooks", "custom-hooks"], premium: false },
    { slug: "javascript-currying", question: "What is currying in JavaScript?", short: "Translating a function with multiple arguments into a sequence of functions that take one argument each.", detailed: "<p>Enables partial application of arguments, creating reusable utility functions. Example: <code>const multiply = a => b => a * b; const double = multiply(2); double(5); // 10</code></p>", rank: 44, difficulty: "medium", tags: ["javascript", "functional", "currying"], premium: false },
    { slug: "single-page-application-seo", question: "How do you optimize Single Page Applications (SPAs) for SEO?", short: "Server-side rendering (SSR), dynamic meta tags, sitemaps, clean routing, and structured schema markup.", detailed: "<p>Crawlers struggle with client-only JS rendering. Solutions: use frameworks supporting SSR/SSG (Next.js), pre-render static pages, generate descriptive page titles and meta headers, and validate search indexing dashboards.</p>", rank: 45, difficulty: "medium", tags: ["seo", "spa", "ssr"], premium: false },
    { slug: "css-flex-basis-grow-shrink", question: "Explain flex-grow, flex-shrink, and flex-basis in CSS.", short: "Grow: how much space to claim; Shrink: how much to compress; Basis: initial element size before sizing.", detailed: "<p><strong>flex-basis:</strong> Initial size of flex item before distribution.</p><p><strong>flex-grow:</strong> Proportional factor to grow if space exists.</p><p><strong>flex-shrink:</strong> Proportional factor to shrink if overflow exists.</p>", rank: 46, difficulty: "easy", tags: ["css", "flexbox", "layout"], premium: false },
    { slug: "react-portal", question: "What are React Portals and when should you use them?", short: "Renders children into a DOM node outside the parent component's hierarchy. Best for modals, tooltips, and dropdowns.", detailed: "<p>Portals allow rendering elements in container root (e.g. body) while maintaining standard React event bubbling. Prevents styling collisions with parent container overflows.</p>", rank: 47, difficulty: "medium", tags: ["react", "portal", "modals"], premium: false },
    { slug: "shadow-dom", question: "Explain the Shadow DOM in Web Components.", short: "Provides style and script encapsulation for self-contained custom widgets, keeping them isolated from global styles.", detailed: "<p>Shadow DOM isolates markup templates from document styles, making it perfect for reusable widget libraries. Used extensively in Web Components specification.</p>", rank: 48, difficulty: "medium", tags: ["web-components", "shadow-dom", "encapsulation"], premium: false },
    { slug: "javascript-weakmap-weakset", question: "Compare Map/Set and WeakMap/WeakSet.", short: "WeakMap/WeakSet hold weak references to objects, allowing garbage collection if no other references exist.", detailed: "<p>Keys in WeakMaps must be objects. Because references are held weakly, they do not prevent garbage collection if the key object is unreferenced elsewhere. Useful for storing metadata or cache keys.</p>", rank: 49, difficulty: "hard", tags: ["javascript", "memory", "weakmap"], premium: true },
    { slug: "web-vitals-fid-inp", question: "Compare First Input Delay (FID) and Interaction to Next Paint (INP).", short: "FID measures latency of the very first user interaction; INP tracks all interactions to report the slowest visual delay.", detailed: "<p>INP replaced FID as a Core Web Vital. INP is more comprehensive because it measures the latency of all page interactions, ensuring the interface remains snappy throughout the session.</p>", rank: 50, difficulty: "hard", tags: ["web-vitals", "performance", "inp", "fid"], premium: true },
    { slug: "frontend-error-boundaries", question: "How do you implement global error boundary handlers in React?", short: "Use class components implementing getDerivedStateFromError and componentDidCatch to render custom fallback views.", detailed: "<p>Error boundaries catch errors during render, lifecycle, or constructors in the tree beneath them. They prevent the entire app from crashing, replacing it with a helpful UI signature.</p>", rank: 51, difficulty: "medium", tags: ["react", "error-boundary", "reliability"], premium: false }
  ];
  fe.forEach(q => all.push(makeQ("frontend", q)));

  // ─── System Design (10 more) ──────────────────────────────────────────
  const sd: Q[] = [
    { slug: "design-geo-hashing", question: "Explain GeoHashing vs QuadTrees for geospatial mapping.", short: "GeoHash maps 2D coordinates to 1D strings; QuadTrees partition space recursively into four quadrants. Both allow proximity queries.", detailed: "<p><strong>GeoHash:</strong> Interleaves bits of longitude and latitude to form a string representing a grid cell. Easy to index in standard DBs (B-trees).</p><p><strong>QuadTree:</strong> Memory-resident tree where each node has 4 children. Best for dynamic queries and fast updates.</p>", rank: 42, difficulty: "hard", tags: ["geospatial", "geohash", "quadtree"], premium: true },
    { slug: "design-nosql-replication", question: "Compare Master-Slave vs Peer-to-Peer database replication.", short: "Master-Slave offers single-write/multi-read with lag; Peer-to-Peer allows multi-write but requires conflict resolution.", detailed: "<p><strong>Master-Slave (Primary-Secondary):</strong> Easy to implement, strong read scale, but single point of write failure. Lag can cause stale reads.</p><p><strong>Peer-to-Peer (Leaderless):</strong> Cassandra/Dynamo. High write availability, writes succeed locally, but requires quorum tuning and merge logic.</p>", rank: 43, difficulty: "medium", tags: ["databases", "replication", "consistency"], premium: false },
    { slug: "design-long-polling-websockets-sse", question: "Compare Long Polling, WebSockets, and Server-Sent Events (SSE).", short: "Long polling is fallback; WebSockets are bi-directional TCP; SSE is unidirectional text stream over HTTP.", detailed: "<p><strong>WebSockets:</strong> Persistent full-duplex TCP channel. Good for games, chat. Heavy resource usage.</p><p><strong>SSE:</strong> Uni-directional server-to-client stream. Runs over HTTP, supports auto-reconnection. Good for stock feeds, scores.</p><p><strong>Long Polling:</strong> Client requests, server holds request open until data arrives. Legacy fallback.</p>", rank: 44, difficulty: "medium", tags: ["real-time", "websockets", "sse"], premium: false },
    { slug: "design-single-sign-on", question: "Design a Single Sign-On (SSO) architecture.", short: "Centralized identity provider issuing JWTs or SAML tokens to service providers.", detailed: "<p><strong>SSO components:</strong> Identity Provider (IdP), Service Providers (SP), auth tokens (OIDC, SAML, JWT). User logs in once at IdP, redirects to SP with cryptographically signed token verified by SP's public key.</p>", rank: 45, difficulty: "hard", tags: ["security", "auth", "sso"], premium: true },
    { slug: "design-ad-click-counter", question: "Design a distributed ad click counter.", short: "Kafka stream receiver, real-time counters in Redis, and periodic aggregate writer to cold storage.", detailed: "<p>Clicks must be counted reliably without double-counting (deduplication) or missing events. Map clicks to Kafka partitions by ad ID, run stream analytics, and write to Redis counters.</p>", rank: 46, difficulty: "hard", tags: ["analytics", "kafka", "redis"], premium: true },
    { slug: "design-distributed-lock", question: "How do you implement distributed locking in microservices?", short: "Use Redlock (Redis) or Zookeeper ephemeral nodes to serialize resource modifications across nodes.", detailed: "<p>Distributed locks guarantee that only one worker node performs an operation. Redis uses set-if-not-exists (NX) with TTL. Redlock uses quorum across multiple Redis nodes for reliability.</p>", rank: 47, difficulty: "medium", tags: ["distributed-systems", "locking", "redis"], premium: false },
    { slug: "design-database-replica-lag", question: "How do you handle read-after-write replica lag issues?", short: "Route critical reads (e.g. user updates) to the primary node, or use session pinning logic.", detailed: "<p>When a user updates details and immediately refreshes, lag on secondary nodes can show old data. Mitigation: (1) Pin reads to primary for 5-10 seconds after writes, (2) Use version tokens to confirm replication, (3) Use local storage caches.</p>", rank: 48, difficulty: "medium", tags: ["databases", "replication", "performance"], premium: false },
    { slug: "design-cache-stampede", question: "What is Cache Stampede and how do you prevent it?", short: "Concurrent cache misses causing database overload. Prevent with mutual exclusion locks or probabilistic early expiration.", detailed: "<p>Also known as dog-piling. When a hot cache key expires, thousands of threads query the database at once. Prevention: (1) Locking: only first thread updates cache, others wait. (2) Probabilistic early expiration: update background before actual TTL ends.</p>", rank: 49, difficulty: "medium", tags: ["caching", "performance", "scalability"], premium: false },
    { slug: "design-bloom-filter-system", question: "Design an image storage deduplication checker using Bloom filters.", short: "Check if file MD5 hash exists in Bloom filter before reading database metadata tables.", detailed: "<p>Bloom filters provide high-speed, low-memory membership verification. When checking if a file upload is a duplicate, run MD5 against Bloom filter. If negative, immediately proceed. If positive, query relational DB to verify.</p>", rank: 50, difficulty: "medium", tags: ["bloom-filter", "deduplication", "storage"], premium: false },
    { slug: "design-saga-pattern", question: "Explain the Saga Pattern for distributed transactions.", short: "Sequence of local transactions, where failure triggers compensating transactions to roll back state changes.", detailed: "<p>Since microservices cannot share a single database transaction, Saga coordinates steps: (1) Service A writes local state, (2) Service B runs next step. If Service C fails, Saga triggers compensating updates backwards.</p>", rank: 51, difficulty: "hard", tags: ["transactions", "microservices", "saga-pattern"], premium: true }
  ];
  sd.forEach(q => all.push(makeQ("system-design", q)));

  // ─── Behavioral (21 more) ─────────────────────────────────────────────
  const bh: Q[] = [
    { slug: "handled-criticism-respectfully", question: "Describe a time you received constructive feedback on your code and how you responded.", short: "Focus on code quality, learning from senior engineers, and applying feedback to future PRs.", detailed: "<p>Show humility and professional growth. Cover: (1) The feedback in the code review, (2) Why your initial code was written that way, (3) The benefits of the proposed solution, (4) How you updated the PR and applied the lesson to subsequent tasks.</p>", rank: 31, difficulty: "easy", tags: ["feedback", "code-review", "teamwork"], premium: false },
    { slug: "prioritized-user-experience", question: "Tell me about a time you advocated for the user experience over technical simplicity.", short: "Pushed for features that improved accessibility or load speeds despite extra dev effort.", detailed: "<p>Describe: (1) The user friction point, (2) The simple technical fallback vs. the premium UI solution, (3) How you got alignment, (4) The positive metrics post-release.</p>", rank: 32, difficulty: "medium", tags: ["user-experience", "accessibility", "product"], premium: false },
    { slug: "worked-with-vague-requirements", question: "Tell me about a time you worked on a project with vague requirements.", short: "Proactively built prototypes, gathered user feedback, and documented assumptions.", detailed: "<p>Demonstrate initiative: define scope, list open assumptions, run alignment meetings, and iterate in small chunks to validate direction.</p>", rank: 33, difficulty: "medium", tags: ["requirements", "ambiguity", "product"], premium: false },
    { slug: "convinced-team-to-refactor", question: "Describe a time you convinced your team to perform a major refactor.", short: "Presented technical debt costs using metrics (slow deploys, bug counts) to win management buy-in.", detailed: "<p>Focus on cost-benefit. Frame technical debt in terms of lost velocity or customer impact, create a phased migration plan, and run pilot conversions.</p>", rank: 34, difficulty: "hard", tags: ["refactoring", "technical-debt", "leadership"], premium: true },
    { slug: "handled-disappointed-client", question: "Tell me about a time you had to deal with a disappointed client or user.", short: "Listen actively, take accountability, and focus on immediate mitigation and long-term fix.", detailed: "<p>Explain: (1) Why the client was unhappy, (2) How you de-escalated the tension by validating their frustrations, (3) The immediate recovery steps, (4) Process improvements to prevent repeats.</p>", rank: 35, difficulty: "medium", tags: ["customer-success", "communication", "de-escalation"], premium: false },
    { slug: "supported-junior-developer", question: "Describe a time you supported a junior developer on your team.", short: "Helped them solve a block using pairing and guided questions rather than fixing it for them.", detailed: "<p>Good mentorship promotes independent problem-solving. Show how you walked through debugging logs, asked clarifying questions, and celebrated their success.</p>", rank: 36, difficulty: "easy", tags: ["mentorship", "coaching", "teamwork"], premium: false },
    { slug: "resolved-deadline-crunch", question: "Tell me about a time you had to manage a sudden deadline crunch.", short: "Scaled down scope, ran standups to clear blockages, and delivered the core MVP on schedule.", detailed: "<p>Detail: (1) The sudden timeline shift, (2) Evaluating trade-offs with product owners, (3) Keeping the team focused on execution, (4) Releasing on time with clean post-launch iterations.</p>", rank: 37, difficulty: "medium", tags: ["deadlines", "time-management", "pressure"], premium: false },
    { slug: "championed-test-coverage", question: "Describe a time you campaigned to improve test coverage in your repository.", short: "Created pre-commit hooks and automated test gates to prevent new regressions.", detailed: "<p>Show how you quantified quality drops, introduced unit testing patterns, made test execution simple, and measured the reduction in production bugs.</p>", rank: 38, difficulty: "medium", tags: ["testing", "quality-assurance", "initiative"], premium: false },
    { slug: "learned-from-failed-launch", question: "Describe a time a product launch did not go as planned.", short: "Maintained poise, rolled back safely, performed a blameless post-mortem, and implemented fixes.", detailed: "<p>Explain: (1) The launch target and the unexpected error, (2) The roll-back coordination, (3) The blameless review, (4) Code updates that prevented the failure on the next attempt.</p>", rank: 39, difficulty: "hard", tags: ["failure", "launch", "post-mortem"], premium: false },
    { slug: "balanced-perfection-with-velocity", question: "Tell me about a time you had to balance perfect code with shipping speed.", short: "Shipped a clean, functional MVP with documented technical debt to capture market windows.", detailed: "<p>Show how you separated critical architectural elements (database design, API endpoints) from visual layout variables that could be refactored later.</p>", rank: 40, difficulty: "medium", tags: ["velocity", "quality", "pragmatism"], premium: false },
    { slug: "introduced-new-tool", question: "Describe introducing a new tool or library to your team's workflow.", short: "Researched options, created a migration prototype, and presented advantages to gain consensus.", detailed: "<p>Explain: (1) The workflow friction point, (2) Evaluating tools (Zustand, Vitest), (3) Running a pilot script, (4) Conducting team walkthroughs to make adoption smooth.</p>", rank: 41, difficulty: "easy", tags: ["tooling", "consensus", "process"], premium: false },
    { slug: "managed-on-call-stress", question: "How do you manage the stress of being on-call for production issues?", short: "Build automated alert dashboards and clear runbooks to make incident response predictable.", detailed: "<p>Stress comes from uncertainty. Reduce stress by organizing clear runbooks for common failures, separating warning alerts from critical paging, and running post-mortems.</p>", rank: 42, difficulty: "medium", tags: ["on-call", "stress-management", "reliability"], premium: false },
    { slug: "pushed-back-on-unrealistic-timeline", question: "Tell me about a time you pushed back on an unrealistic timeline.", short: "Presented estimate break-downs and resource allocations to negotiate a phased rollout.", detailed: "<p>Show how you decomposed the feature backlog, demonstrated developer allocation limits, and worked with product management to define phase 1 deliverables.</p>", rank: 43, difficulty: "medium", tags: ["timeline", "negotiation", "scoping"], premium: false },
    { slug: "helped-team-adopt-scrum", question: "Describe helping your team adopt agile or scrum ceremonies.", short: "Facilitated short daily standups and retrospectives to surface blocks and improve velocity.", detailed: "<p>Focus on team collaboration: showing how standups saved meeting overhead and how blameless retrospectives let developers fix process bottlenecks.</p>", rank: 44, difficulty: "easy", tags: ["agile", "scrum", "process"], premium: false },
    { slug: "dealt-with-remote-isolation", question: "How do you maintain team connection and prevent isolation in remote settings?", short: "Schedule async pairing sessions, share status updates openly, and participate in casual virtual meets.", detailed: "<p>Explain: (1) Proactive communication habits, (2) Scheduling regular code pairing blocks, (3) Documenting design notes to encourage collaboration.</p>", rank: 45, difficulty: "easy", tags: ["remote-work", "communication", "team-morale"], premium: false },
    { slug: "deprecated-legacy-system", question: "Tell me about a time you successfully deprecated a legacy system.", short: "Mapped dependencies, migrated users in phases, and monitored traffic to ensure safe shutdown.", detailed: "<p>Deprecated systems run maintenance costs. Outline: (1) Identifying active users, (2) Building modern API paths, (3) Toggle flags to route traffic, (4) Final verification before deletion.</p>", rank: 46, difficulty: "hard", tags: ["migration", "deprecation", "legacy"], premium: true },
    { slug: "resolved-pr-gridlock", question: "Describe resolving a deadlock or gridlock in a pull request discussion.", short: "Took the conversation to a video call to discuss design trade-offs and reach a compromise.", detailed: "<p>When text reviews become circular, synchronous discussion helps. Describe: (1) The technical disagreement, (2) Scheduling a quick sync, (3) Agreeing on metrics, (4) Merging the PR.</p>", rank: 47, difficulty: "medium", tags: ["code-review", "conflict", "communication"], premium: false },
    { slug: "automated-manual-task", question: "Tell me about a time you automated a manual task that saved time.", short: "Created shell scripts and cron jobs to automate database seeding or environment cleanup.", detailed: "<p>Demonstrate efficiency: (1) The repetitive manual workflow (e.g. database setup), (2) Building a clean automation script, (3) Saving hours of engineer setup time.</p>", rank: 48, difficulty: "easy", tags: ["automation", "efficiency", "scripting"], premium: false },
    { slug: "handled-scope-creep", question: "Describe handling scope creep on a critical project.", short: "Logged new requests in the backlog and negotiated scope swaps to maintain target dates.", detailed: "<p>Scope creep endangers deadlines. Explain how you documented requests, estimated engineering hours, and worked with product management to maintain focus on the core MVP.</p>", rank: 49, difficulty: "medium", tags: ["project-management", "scope-creep", "negotiation"], premium: false },
    { slug: "improved-onboarding-docs", question: "Tell me about a time you improved onboarding documentation.", short: "Updated setup guides and created helper scripts to help new hires run the local dev environment on day one.", detailed: "<p>Onboarding velocity is key for growing teams. Explain how you revised setup instructions, fixed stale links, and created a single command startup flow.</p>", rank: 50, difficulty: "easy", tags: ["onboarding", "documentation", "process"], premium: false },
    { slug: "worked-with-cross-functional-partners", question: "Describe working closely with marketing or sales to design a feature.", short: "Collaborated to understand market demand and design billing tiers that matched buyer behaviors.", detailed: "<p>Outline: (1) Meeting partners to understand target users, (2) Translating business objectives into database properties, (3) Deploying and verifying conversions.</p>", rank: 51, difficulty: "medium", tags: ["collaboration", "cross-functional", "product"], premium: false }
  ];
  bh.forEach(q => all.push(makeQ("behavioral", q)));

  // ─── Technical — Core CS (18 more) ──────────────────────────────────────
  const tc: Q[] = [
    { slug: "symmetric-vs-asymmetric-encryption", question: "Compare symmetric and asymmetric encryption.", short: "Symmetric uses one shared key for encryption/decryption; asymmetric uses a public/private key pair.", detailed: "<p><strong>Symmetric (e.g. AES):</strong> Fast, optimized for large payloads. Key exchange is the core challenge. If key leaked, security compromised.</p><p><strong>Asymmetric (e.g. RSA, ECC):</strong> Slower. Anyone can encrypt with public key; only holder of private key can decrypt. Best for key exchange and digital signatures.</p><p><strong>Hybrid:</strong> TLS uses asymmetric to exchange a symmetric key, then encrypts session traffic symmetrically.</p>", rank: 33, difficulty: "medium", tags: ["security", "cryptography", "ssl-tls"], premium: false },
    { slug: "jwt-token-structure", question: "Explain the structure of a JSON Web Token (JWT).", short: "Consists of three parts separated by dots: Header, Payload, and Signature.", detailed: "<p><strong>Header:</strong> Specifies token type (JWT) and hashing algorithm (HS256/RS256).</p><p><strong>Payload:</strong> Contains claims (user info, roles, expiration timestamp). Base64Url encoded.</p><p><strong>Signature:</strong> Generated by hashing encoded header and payload with a secret key, verifying authenticity.</p>", rank: 34, difficulty: "easy", tags: ["auth", "security", "jwt"], premium: false },
    { slug: "os-virtual-memory", question: "How does virtual memory work in operating systems?", short: "Uses pagetables and disk storage (swap space) to let programs address more memory than physically available.", detailed: "<p>Virtual memory maps virtual addresses used by programs to physical RAM addresses. If RAM is full, the OS moves inactive blocks (pages) to disk (paging/swapping). On access, a page fault occurs and pages are swapped back.</p>", rank: 35, difficulty: "medium", tags: ["os", "memory-management", "virtual-memory"], premium: false },
    { slug: "database-normalization-forms", question: "Explain database normalization (1NF, 2NF, 3NF).", short: "Process of organizing tables to minimize redundancy and dependency anomalies.", detailed: "<p><strong>1NF:</strong> Atomic values, unique row names, no repeating groups.</p><p><strong>2NF:</strong> Meets 1NF, and all non-key attributes fully depend on primary key (no partial dependency).</p><p><strong>3NF:</strong> Meets 2NF, and no transitive dependencies (columns depend only on primary key, not other non-key columns).</p>", rank: 36, difficulty: "medium", tags: ["databases", "normalization", "relational"], premium: false },
    { slug: "nosql-eventual-consistency", question: "What is eventual consistency and how is it achieved?", short: "A consistency model guaranteeing all replicas will eventually sync if no new updates are made.", detailed: "<p>Common in distributed databases (Cassandra, DynamoDB). Achieved via anti-entropy protocols, read repair, gossip protocol syncs, or conflict-resolution strategies like Last-Write-Wins (LWW) or Vector Clocks.</p>", rank: 37, difficulty: "medium", tags: ["consistency", "nosql", "distributed-systems"], premium: false },
    { slug: "http-status-codes-groups", question: "Explain HTTP status code groups (1xx, 2xx, 3xx, 4xx, 5xx).", short: "1xx: informational; 2xx: success; 3xx: redirect; 4xx: client error; 5xx: server error.", detailed: "<p><strong>1xx:</strong> Informational (e.g. 101 Switching Protocols). <strong>2xx:</strong> Success (200 OK, 201 Created). <strong>3xx:</strong> Redirection (301 Permanent, 302 Found, 304 Not Modified). <strong>4xx:</strong> Client Error (400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found). <strong>5xx:</strong> Server Error (500 Internal, 502 Bad Gateway, 503 Unavailable).</p>", rank: 38, difficulty: "easy", tags: ["http", "protocols", "fundamentals"], premium: false },
    { slug: "websockets-vs-http", question: "Compare WebSockets and HTTP.", short: "HTTP is request-response client-initiated; WebSockets offer persistent, bi-directional, full-duplex communication.", detailed: "<p>HTTP is connectionless (per request) and unidirectional. WebSockets begin with an HTTP handshake, then upgrade the connection to a persistent TCP socket allowing server-push and client-send concurrently with minimal frame overhead.</p>", rank: 39, difficulty: "easy", tags: ["networking", "http", "websockets"], premium: false },
    { slug: "compilers-vs-interpreters", question: "Compare compilers and interpreters.", short: "Compilers translate entire code to machine binary beforehand; interpreters translate and execute line-by-line at runtime.", detailed: "<p><strong>Compiler:</strong> Faster execution, longer build times, error detection before execution. Examples: C++, Rust.</p><p><strong>Interpreter:</strong> Faster development cycle, slower execution, dynamic parsing. Examples: Python, Ruby.</p><p><strong>JIT (Just-In-Time):</strong> Hybird compiling hot paths at runtime. Used by JS V8 engine.</p>", rank: 40, difficulty: "easy", tags: ["compilers", "runtime", "fundamentals"], premium: false },
    { slug: "graph-topological-cycle-detection", question: "How do you detect cycles in directed graphs?", short: "Run DFS and check if we encounter a node currently in the recursion stack (back-edge).", detailed: "<p>Use coloring (white = unvisited, gray = in recursion stack, black = fully processed). If DFS visits a gray node, a cycle exists. Alternatively, Kahn's algorithm fails to process all nodes if a cycle exists.</p>", rank: 41, difficulty: "hard", tags: ["graphs", "cycle-detection", "dfs", "algorithms"], premium: true },
    { slug: "tree-traversals", question: "Explain tree traversals (In-order, Pre-order, Post-order, Level-order).", short: "DFS variants visiting nodes in different sequence orders, and BFS level-by-level traversal.", detailed: "<p><strong>In-order:</strong> Left → Root → Right. Prints BST in sorted order.</p><p><strong>Pre-order:</strong> Root → Left → Right. Used to clone trees.</p><p><strong>Post-order:</strong> Left → Right → Root. Used in deletion and bottom-up metrics.</p><p><strong>Level-order:</strong> Breadth-first queue traversal.</p>", rank: 42, difficulty: "easy", tags: ["trees", "traversal", "fundamentals"], premium: false },
    { slug: "binary-search-recursive-iterative", question: "Compare recursive and iterative implementations of binary search.", short: "Iterative runs in O(1) space; recursive runs in O(log n) space due to recursion call stack.", detailed: "<p>Both have O(log n) time complexity. However, recursion requires active stack frames for each division. Iterative uses loop updates on low/high bounds, avoiding stack overflow risks entirely.</p>", rank: 43, difficulty: "easy", tags: ["binary-search", "recursion", "algorithms"], premium: false },
    { slug: "hash-function-qualities", question: "What makes a good cryptographic hash function?", short: "Deterministic, fast computation, collision-resistant, pre-image resistant, and avalanche effect.", detailed: "<p><strong>Deterministic:</strong> Same input always yields same output.</p><p><strong>Collision-resistant:</strong> Extremely hard to find two different inputs with same hash.</p><p><strong>Avalanche effect:</strong> Small input change produces completely different hash.</p><p><strong>Pre-image resistant:</strong> Infeasible to reverse hash to find input.</p>", rank: 44, difficulty: "medium", tags: ["security", "hashing", "cryptography"], premium: false },
    { slug: "distributed-consensus-paxos-raft", question: "Explain distributed consensus and compare Paxos and Raft.", short: "Protocols to agree on a state or transaction log across multiple nodes, even if some fail.", detailed: "<p>Distributed consensus solves split-brain issues. <strong>Paxos:</strong> Formally correct but notoriously complex to implement. <strong>Raft:</strong> Structured for understandability. Divides consensus into Leader Election, Log Replication, and Safety.</p>", rank: 45, difficulty: "hard", tags: ["consensus", "raft", "paxos", "distributed-systems"], premium: true },
    { slug: "database-optimistic-locking", question: "Explain Optimistic vs Pessimistic concurrency control in databases.", short: "Optimistic assumes no collision and checks before commit; pessimistic locks resources beforehand.", detailed: "<p><strong>Optimistic (OCC):</strong> Uses version columns. UPDATE WHERE version = 1. Fast for read-heavy systems with low contention. Rejects write if version changed.</p><p><strong>Pessimistic:</strong> SELECT FOR UPDATE. Holds lock until transaction ends. Prevents concurrency but can cause deadlocks and delays.</p>", rank: 46, difficulty: "medium", tags: ["concurrency", "databases", "locking"], premium: false },
    { slug: "mvc-architecture-pattern", question: "Describe the Model-View-Controller (MVC) pattern.", short: "Decouples application logic (Model), user interface (View), and input controller (Controller).", detailed: "<p><strong>Model:</strong> Manages state, schemas, and business rules.</p><p><strong>View:</strong> Renders visual data representation (UI).</p><p><strong>Controller:</strong> Listens to requests/inputs, updates Model, and determines target View response.</p>", rank: 47, difficulty: "easy", tags: ["mvc", "architecture", "patterns"], premium: false },
    { slug: "microservices-saga-vs-two-phase-commit", question: "Compare Saga and Two-Phase Commit (2PC) for distributed transactions.", short: "2PC guarantees ACID but blocks; Saga is eventual consistency with compensating rollbacks.", detailed: "<p><strong>2PC:</strong> Coordinator asks nodes to prepare, then commits. High latency, blocking, doesn't scale. <strong>Saga:</strong> Sequence of local transactions. Compensation handles failures async. Scale-friendly, eventual consistency.</p>", rank: 48, difficulty: "hard", tags: ["transactions", "saga", "2pc", "distributed-systems"], premium: true },
    { slug: "load-balancer-algorithms", question: "Compare Round Robin, Least Connections, and Consistent Hashing in load balancers.", short: "Round robin splits sequentially; Least connections checks worker load; Consistent hashing route based on client IP hash.", detailed: "<p><strong>Round Robin:</strong> Simple, assumes equal server capacity. <strong>Least Connections:</strong> Evaluates active connection count, ideal for long-lived tasks. <strong>Consistent Hashing:</strong> Ensures sticky sessions to the same server node based on client properties.</p>", rank: 49, difficulty: "medium", tags: ["load-balancing", "networking", "algorithms"], premium: false },
    { slug: "redis-persistence-rdb-aof", question: "Compare Redis RDB snapshots and AOF logs.", short: "RDB takes point-in-time binary snapshots; AOF logs every write command sequentially.", detailed: "<p><strong>RDB (Redis Database):</strong> Compact, fast restarts, but risk of losing data since last snapshot. <strong>AOF (Append Only File):</strong> Very durable, command log is appended. Larger file size, slower restarts. Hybrid configuration is common.</p>", rank: 50, difficulty: "medium", tags: ["redis", "persistence", "databases"], premium: false }
  ];
  tc.forEach(q => all.push(makeQ("technical-core", q)));

  return all;
}

async function seedBatch3() {
  console.log("🌱 Phase 6 — Batch 3 Content Seeding");
  console.log("=====================================\n");

  await mongoose.connect(MONGODB_URI!);
  console.log("[DB] Connected\n");

  const allCats = await Category.find({});
  const slugToId: Record<string, string> = {};
  for (const cat of allCats) { slugToId[cat.slug] = cat._id.toString(); }

  const questions = batch3Questions();
  console.log(`📝 Seeding ${questions.length} additional questions...`);

  let created = 0, skipped = 0;
  for (const q of questions) {
    const categoryId = slugToId[q.categorySlug];
    if (!categoryId) { console.error(`  ❌ Missing category: ${q.categorySlug}`); skipped++; continue; }
    const exists = await Question.findOne({ slug: q.slug });
    if (exists) { skipped++; continue; }
    await Question.create({ category: categoryId, slug: q.slug, question: q.question, answer: q.answer, videos: [], difficulty: q.difficulty, frequencyRank: q.frequencyRank, tags: q.tags, isPremium: q.isPremium, isPublished: true });
    created++;
  }

  console.log(`  ✚ Created: ${created}`);
  console.log(`  ⏭ Skipped: ${skipped}\n`);

  console.log("📊 Updating category question counts...");
  for (const cat of allCats) {
    const count = await Question.countDocuments({ category: cat._id, isPublished: true });
    await Category.updateOne({ _id: cat._id }, { $set: { questionCount: count } });
    console.log(`  ${cat.name}: ${count} questions`);
  }

  console.log("\n✅ Batch 3 complete!");
  await mongoose.disconnect();
  process.exit(0);
}

seedBatch3().catch(err => { console.error("❌", err); process.exit(1); });
