/**
 * Phase 6 — Additional Content Seeding (Batch 2)
 *
 * Fills System Design, Behavioral, Frontend, and Technical categories
 * to 50+ questions each.
 *
 * Usage: npx tsx scripts/seed-content-batch2.ts
 */

import mongoose from "mongoose";
import path from "path";
import fs from "fs";

function loadEnv() {
  const envPath = path.resolve(process.cwd(), ".env.local");
  const fallbackEnvPath = path.resolve(process.cwd(), ".env");
  let envFile = "";
  if (fs.existsSync(envPath)) { envFile = fs.readFileSync(envPath, "utf-8"); }
  else if (fs.existsSync(fallbackEnvPath)) { envFile = fs.readFileSync(fallbackEnvPath, "utf-8"); }
  else { console.warn("[Seed] Warning: No .env.local or .env file found."); return; }
  envFile.split("\n").forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return;
    const parts = trimmed.split("=");
    if (parts.length >= 2) { process.env[parts[0].trim()] = parts.slice(1).join("=").trim().replace(/^['"]|['"]$/g, ""); }
  });
}
loadEnv();

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) { console.error("❌ MONGODB_URI missing"); process.exit(1); }

const categorySchema = new mongoose.Schema({ name: String, slug: { type: String, unique: true }, type: String, description: String, icon: String, order: Number, questionCount: Number, isPublished: Boolean }, { timestamps: true });
const questionSchema = new mongoose.Schema({ category: { type: mongoose.Schema.Types.ObjectId, ref: "Category" }, slug: { type: String, unique: true }, question: String, answer: { short: String, detailed: String, example: String }, videos: [{ label: String, url: String, order: Number }], difficulty: String, frequencyRank: Number, tags: [String], isPremium: Boolean, isPublished: Boolean }, { timestamps: true });
const Category = mongoose.models.Category || mongoose.model("Category", categorySchema);
const Question = mongoose.models.Question || mongoose.model("Question", questionSchema);

interface Q { slug: string; question: string; short: string; detailed: string; example?: string; difficulty: "easy"|"medium"|"hard"; rank: number; tags: string[]; premium: boolean; }

function makeQ(catSlug: string, q: Q) {
  return { categorySlug: catSlug, slug: q.slug, question: q.question, answer: { short: q.short, detailed: q.detailed, example: q.example || "" }, difficulty: q.difficulty, frequencyRank: q.rank, tags: q.tags, isPremium: q.premium };
}

function batch2Questions() {
  const all: ReturnType<typeof makeQ>[] = [];

  // ─── System Design (40 more) ──────────────────────────────────────────
  const sd: Q[] = [
    { slug: "design-instagram", question: "Design Instagram's photo sharing system.", short: "Object storage for images, CDN delivery, news feed with fan-out, and metadata in relational DB.", detailed: "<p><strong>Storage:</strong> S3/GCS for images with multiple resolutions. CDN for delivery. Metadata (captions, likes, comments) in PostgreSQL.</p><p><strong>Feed:</strong> Hybrid fan-out (push for <10K followers, pull for celebrities). Redis for timeline cache.</p><p><strong>Search:</strong> Elasticsearch for hashtags and user search. Explore feed via ML recommendations.</p>", rank: 11, difficulty: "hard", tags: ["photo-sharing", "cdn", "feed-system"], premium: true },
    { slug: "design-uber", question: "Design a ride-sharing service like Uber.", short: "Location-based matching, geospatial indexing, real-time tracking, and surge pricing.", detailed: "<p><strong>Core flow:</strong> Rider requests ride → Match with nearby driver → Real-time tracking → Payment.</p><p><strong>Location:</strong> Geospatial index (QuadTree/GeoHash) for finding nearby drivers. WebSocket for real-time location updates.</p><p><strong>Matching:</strong> ETA-based matching considering driver location, traffic, and rider preferences.</p><p><strong>Surge:</strong> Dynamic pricing based on supply/demand ratio in geo-cells.</p>", rank: 12, difficulty: "hard", tags: ["geospatial", "real-time", "matching"], premium: true },
    { slug: "design-youtube", question: "Design YouTube's video streaming platform.", short: "Upload pipeline with transcoding, adaptive bitrate streaming, CDN distribution, and recommendation engine.", detailed: "<p><strong>Upload:</strong> Chunked upload → Object storage → Transcoding pipeline (multiple resolutions/codecs) → CDN distribution.</p><p><strong>Streaming:</strong> Adaptive bitrate (HLS/DASH). CDN edge servers. Pre-buffer and quality switching.</p><p><strong>Metadata:</strong> Video info in SQL, comments in NoSQL, search via Elasticsearch.</p><p><strong>Recommendations:</strong> Collaborative filtering + content-based ML models.</p>", rank: 13, difficulty: "hard", tags: ["video-streaming", "transcoding", "cdn"], premium: true },
    { slug: "design-google-docs", question: "Design a collaborative document editor like Google Docs.", short: "Operational Transformation or CRDTs for conflict resolution, WebSocket for real-time sync.", detailed: "<p><strong>Real-time collaboration:</strong> Operational Transformation (OT) or Conflict-free Replicated Data Types (CRDTs) to handle concurrent edits.</p><p><strong>Architecture:</strong> WebSocket connections for real-time sync. Document stored as operation log. Periodic snapshots for fast loading.</p><p><strong>Cursors:</strong> Broadcast cursor positions via presence channel. Color-coded per user.</p>", rank: 14, difficulty: "hard", tags: ["collaboration", "crdt", "real-time"], premium: true },
    { slug: "design-tinyurl-analytics", question: "Design analytics for a URL shortener.", short: "Event streaming pipeline, time-series aggregation, and real-time dashboards.", detailed: "<p><strong>Data collection:</strong> Each redirect generates a click event (timestamp, IP, user-agent, referer). Events published to Kafka.</p><p><strong>Processing:</strong> Stream processing (Flink/Spark Streaming) for real-time counts. Batch jobs for historical analytics.</p><p><strong>Storage:</strong> Time-series DB (InfluxDB/TimescaleDB) for metrics. Pre-aggregated rollups for dashboard queries.</p>", rank: 15, difficulty: "medium", tags: ["analytics", "event-streaming", "time-series"], premium: false },
    { slug: "design-payment-system", question: "Design a payment processing system.", short: "Idempotent transactions, PCI compliance, double-entry ledger, and reconciliation.", detailed: "<p><strong>Core principles:</strong> Idempotency keys prevent duplicate charges. Double-entry accounting for audit trail. PCI DSS compliance for card data.</p><p><strong>Flow:</strong> Payment intent → Authorization → Capture → Settlement. Each step is idempotent and retryable.</p><p><strong>Security:</strong> Tokenization (never store raw card data), fraud detection ML, rate limiting, and 3D Secure for authentication.</p>", rank: 16, difficulty: "hard", tags: ["payments", "idempotency", "security"], premium: true },
    { slug: "design-search-engine", question: "Design a web search engine.", short: "Web crawler, inverted index, PageRank scoring, and query processing pipeline.", detailed: "<p><strong>Crawling:</strong> Distributed web crawler with politeness policies, URL frontier, and deduplication.</p><p><strong>Indexing:</strong> Inverted index mapping terms to document lists. TF-IDF scoring. Positional index for phrase queries.</p><p><strong>Ranking:</strong> PageRank (link analysis) + relevance scoring + freshness + personalization.</p><p><strong>Serving:</strong> Sharded index across many servers. Query parsing, spell correction, autocomplete.</p>", rank: 17, difficulty: "hard", tags: ["search", "inverted-index", "pagerank"], premium: true },
    { slug: "design-dropbox", question: "Design a file storage and sync service like Dropbox.", short: "Chunked file storage, delta sync, conflict resolution, and cross-device synchronization.", detailed: "<p><strong>Storage:</strong> Files split into chunks (4MB). Each chunk content-addressed (SHA-256 hash). Deduplication across users.</p><p><strong>Sync:</strong> Client monitors file changes. Delta sync — only upload changed chunks. Server notifies other devices via long-polling or WebSocket.</p><p><strong>Conflict resolution:</strong> Last-writer-wins with conflict copies for manual resolution.</p>", rank: 18, difficulty: "hard", tags: ["file-sync", "chunking", "deduplication"], premium: false },
    { slug: "design-web-crawler", question: "Design a scalable web crawler.", short: "URL frontier, politeness queues, distributed workers, and deduplication.", detailed: "<p><strong>Architecture:</strong> URL Frontier (priority queue of URLs to crawl) → Distributed fetch workers → Content extraction → Link extraction → URL Frontier.</p><p><strong>Politeness:</strong> Per-domain rate limiting, respect robots.txt, crawl-delay headers.</p><p><strong>Deduplication:</strong> URL normalization + content fingerprinting (SimHash) to avoid duplicates.</p><p><strong>Scale:</strong> Consistent hashing to distribute domains across workers. Bloom filter for visited URL check.</p>", rank: 19, difficulty: "medium", tags: ["crawler", "distributed", "deduplication"], premium: false },
    { slug: "design-parking-lot", question: "Design a parking lot management system.", short: "Object-oriented design with vehicle types, spot allocation, and payment processing.", detailed: "<p><strong>Classes:</strong> ParkingLot, Level, ParkingSpot (Small/Medium/Large), Vehicle (Motorcycle/Car/Bus), Ticket, PaymentProcessor.</p><p><strong>Allocation:</strong> Find available spot matching vehicle size. Assign nearest to entrance. Track occupancy per level.</p><p><strong>Payment:</strong> Hourly rates by vehicle type. Ticket tracks entry time. Payment on exit.</p>", rank: 20, difficulty: "easy", tags: ["oop", "low-level-design", "parking"], premium: false },
    { slug: "design-leaderboard", question: "Design a real-time gaming leaderboard.", short: "Redis sorted sets for O(log n) rank operations with periodic persistence to SQL.", detailed: "<p><strong>Core:</strong> Redis Sorted Set (ZADD, ZRANK, ZRANGE) provides O(log n) insert, O(log n) rank lookup, O(log n + k) range queries.</p><p><strong>Scale:</strong> Partition by game/region. Top-N cached separately for hot reads.</p><p><strong>Persistence:</strong> Periodic flush to SQL for history. Event sourcing for score audit trail.</p>", rank: 21, difficulty: "medium", tags: ["leaderboard", "redis", "sorted-set"], premium: false },
    { slug: "design-email-system", question: "Design an email service like Gmail.", short: "SMTP for sending, IMAP for retrieval, full-text search, spam filtering, and attachment storage.", detailed: "<p><strong>Sending:</strong> SMTP protocol. MX record lookup for recipient domain. Queue-based delivery with retry.</p><p><strong>Storage:</strong> Email body in object storage. Metadata in relational DB. Attachments in blob storage.</p><p><strong>Search:</strong> Elasticsearch for full-text email search. Label/folder system via tags.</p><p><strong>Spam:</strong> ML classifier using sender reputation, content analysis, user feedback signals.</p>", rank: 22, difficulty: "hard", tags: ["email", "smtp", "search"], premium: true },
    { slug: "design-api-gateway", question: "Design an API gateway.", short: "Request routing, authentication, rate limiting, circuit breaking, and request/response transformation.", detailed: "<p><strong>Core functions:</strong> Request routing, load balancing, authentication/authorization, rate limiting, request transformation, response caching, circuit breaking, logging/monitoring.</p><p><strong>Architecture:</strong> Reverse proxy pattern. Plugin-based for extensibility. Configuration via admin API.</p><p><strong>Patterns:</strong> Backend-for-Frontend (BFF), API composition, protocol translation (REST to gRPC).</p>", rank: 23, difficulty: "medium", tags: ["api-gateway", "microservices", "routing"], premium: false },
    { slug: "design-distributed-cache", question: "Design a distributed caching system like Memcached.", short: "Consistent hashing, LRU eviction, replication, and client-side sharding.", detailed: "<p><strong>Partitioning:</strong> Consistent hashing distributes keys across cache nodes. Virtual nodes for even distribution.</p><p><strong>Eviction:</strong> LRU (Least Recently Used) when memory is full. TTL-based expiration for freshness.</p><p><strong>Replication:</strong> Optional async replication to backup nodes for high availability.</p><p><strong>Client:</strong> Client-side consistent hashing library routes to correct node. Connection pooling for efficiency.</p>", rank: 24, difficulty: "medium", tags: ["caching", "distributed", "consistent-hashing"], premium: false },
    { slug: "design-ticketing-system", question: "Design an event ticketing system like Ticketmaster.", short: "Seat locking with TTL, queue-based checkout, and inventory management with optimistic concurrency.", detailed: "<p><strong>Challenges:</strong> High concurrency during on-sale events. Prevent overselling. Fair queuing.</p><p><strong>Seat selection:</strong> Temporary lock with TTL (10 min). Optimistic concurrency control on checkout.</p><p><strong>Queue:</strong> Virtual waiting room during high demand. Token-based access to purchase flow.</p><p><strong>Inventory:</strong> Pre-computed seat maps. Atomic decrement of available count. Saga pattern for payment + ticket allocation.</p>", rank: 25, difficulty: "hard", tags: ["ticketing", "concurrency", "inventory"], premium: true },
    { slug: "design-logging-system", question: "Design a centralized logging and monitoring system.", short: "ELK stack pattern: log collection, streaming, indexing, search, alerting, and dashboards.", detailed: "<p><strong>Collection:</strong> Agents on each server (Filebeat/Fluentd) ship logs. Structured logging (JSON).</p><p><strong>Transport:</strong> Kafka as buffer between collection and processing. Handles spikes.</p><p><strong>Processing:</strong> Logstash/Flink for parsing, enrichment, and routing.</p><p><strong>Storage:</strong> Elasticsearch for searchable index. Cold storage (S3) for archives.</p><p><strong>Visualization:</strong> Kibana/Grafana dashboards. Alerting rules for anomaly detection.</p>", rank: 26, difficulty: "medium", tags: ["logging", "elk", "monitoring"], premium: false },
    { slug: "design-task-scheduler", question: "Design a distributed task scheduler.", short: "Priority queues, cron-like scheduling, worker pools, and exactly-once execution guarantees.", detailed: "<p><strong>Components:</strong> Scheduler (cron parser, job queue), Worker pool (execute tasks), Coordinator (assign jobs, track status).</p><p><strong>Reliability:</strong> Persistent job queue (Redis/PostgreSQL). Heartbeat-based worker health. Dead letter queue for failed jobs. At-least-once with idempotent tasks.</p><p><strong>Scheduling:</strong> Cron expressions, one-time delays, recurring intervals. Priority-based execution order.</p>", rank: 27, difficulty: "medium", tags: ["scheduler", "distributed", "worker-pool"], premium: false },
    { slug: "design-food-delivery", question: "Design a food delivery platform like DoorDash.", short: "Restaurant catalog, order management, driver matching, real-time tracking, and ETAs.", detailed: "<p><strong>Services:</strong> Restaurant catalog + menu, Order management, Payment, Driver matching, Real-time tracking, ETA prediction.</p><p><strong>Matching:</strong> Assign orders to nearby drivers considering: distance to restaurant, current orders, driver rating. Batch matching for efficiency.</p><p><strong>ETA:</strong> ML model using: historical delivery times, current traffic, restaurant prep time, driver location.</p>", rank: 28, difficulty: "hard", tags: ["food-delivery", "matching", "real-time"], premium: true },
    { slug: "design-metrics-collection", question: "Design a metrics collection and aggregation system.", short: "Push/pull collection, time-series storage, pre-aggregation, and alerting pipelines.", detailed: "<p><strong>Collection:</strong> Push model (StatsD — app pushes metrics) or Pull model (Prometheus — scrapes endpoints).</p><p><strong>Storage:</strong> Time-series database optimized for append-heavy writes and range queries (InfluxDB, Prometheus TSDB).</p><p><strong>Aggregation:</strong> Pre-compute rollups (1min → 5min → 1hr → 1day). Downsampling for long-term storage.</p><p><strong>Alerting:</strong> Rules engine evaluating thresholds. PagerDuty/Slack integration. Anomaly detection.</p>", rank: 29, difficulty: "medium", tags: ["metrics", "time-series", "monitoring"], premium: false },
    { slug: "design-social-graph", question: "Design a social graph service.", short: "Graph database for relationships, adjacency lists for fast traversal, and caching for frequent queries.", detailed: "<p><strong>Storage:</strong> Graph DB (Neo4j) or adjacency list in relational DB. Edge table: (user_id, friend_id, relationship_type, created_at).</p><p><strong>Operations:</strong> Add/remove connection, get friends, get friends-of-friends, mutual friends, shortest path.</p><p><strong>Scale:</strong> Shard by user_id. Cache hot users' friend lists in Redis. Eventual consistency for non-critical operations.</p>", rank: 30, difficulty: "medium", tags: ["social-graph", "graph-database", "relationships"], premium: false },
    { slug: "cap-theorem-explained", question: "Explain the CAP theorem and its practical implications.", short: "In a distributed system, you can only guarantee 2 of 3: Consistency, Availability, Partition tolerance.", detailed: "<p><strong>CAP:</strong> During a network partition, you must choose between Consistency (all nodes see the same data) and Availability (every request gets a response).</p><p><strong>CP systems:</strong> HBase, MongoDB (in some configs). Sacrifice availability during partitions.</p><p><strong>AP systems:</strong> Cassandra, DynamoDB. Sacrifice consistency, use eventual consistency.</p><p><strong>Reality:</strong> PACELC theorem is more practical — even without partitions, there's a latency vs. consistency trade-off.</p>", rank: 31, difficulty: "medium", tags: ["cap-theorem", "distributed-systems", "consistency"], premium: false },
    { slug: "microservices-vs-monolith", question: "When would you choose microservices over a monolith?", short: "Monolith for small teams and early stage. Microservices when scaling teams and independent deployability matter.", detailed: "<p><strong>Monolith advantages:</strong> Simpler development, testing, deployment. Lower operational overhead. Better for small teams (<10 engineers).</p><p><strong>Microservices advantages:</strong> Independent deployment, technology diversity, team autonomy, fault isolation, horizontal scaling per service.</p><p><strong>Migration path:</strong> Start monolith, extract services at domain boundaries when scaling demands it. Strangler fig pattern for gradual migration.</p>", rank: 32, difficulty: "medium", tags: ["microservices", "monolith", "architecture"], premium: false },
    { slug: "event-driven-architecture", question: "Explain event-driven architecture patterns.", short: "Publish-subscribe, event sourcing, and CQRS for decoupled, scalable systems.", detailed: "<p><strong>Pub/Sub:</strong> Producers publish events to topics. Consumers subscribe independently. Decouples services.</p><p><strong>Event Sourcing:</strong> Store state as sequence of events instead of current state. Enables replay, audit, and temporal queries.</p><p><strong>CQRS:</strong> Separate read and write models. Optimize each independently. Eventually consistent reads.</p><p><strong>Tools:</strong> Kafka, RabbitMQ, AWS EventBridge, Redis Streams.</p>", rank: 33, difficulty: "medium", tags: ["event-driven", "cqrs", "event-sourcing"], premium: false },
    { slug: "database-sharding-strategies", question: "Describe database sharding strategies.", short: "Hash-based, range-based, and directory-based sharding with trade-offs for each approach.", detailed: "<p><strong>Hash-based:</strong> Hash(key) % N determines shard. Even distribution but poor for range queries. Resharding is expensive.</p><p><strong>Range-based:</strong> Key ranges assigned to shards (e.g., users A-M shard 1, N-Z shard 2). Good for range queries. Risk of hot spots.</p><p><strong>Directory-based:</strong> Lookup table maps keys to shards. Flexible but adds a lookup hop.</p><p><strong>Challenges:</strong> Cross-shard queries, distributed transactions, resharding/rebalancing.</p>", rank: 34, difficulty: "hard", tags: ["sharding", "databases", "scalability"], premium: false },
    { slug: "design-object-storage", question: "Design an object storage system like S3.", short: "Content-addressable storage, metadata service, replication, and lifecycle management.", detailed: "<p><strong>Architecture:</strong> Metadata service (key → storage location) + Data nodes (store actual bytes).</p><p><strong>Storage:</strong> Content-addressable by hash. Erasure coding (Reed-Solomon) for durability with less overhead than full replication.</p><p><strong>Consistency:</strong> Read-after-write consistency for PUTs. Eventual consistency for DELETEs.</p><p><strong>Features:</strong> Versioning, lifecycle policies, access control (bucket/object level), multipart upload for large files.</p>", rank: 35, difficulty: "hard", tags: ["object-storage", "s3", "distributed-storage"], premium: true },
    { slug: "design-message-queue", question: "Design a distributed message queue.", short: "Partitioned topics, consumer groups, at-least-once delivery, and ordered processing.", detailed: "<p><strong>Core:</strong> Producers → Topics (partitioned) → Consumer Groups. Messages stored durably on disk.</p><p><strong>Ordering:</strong> Guaranteed within a partition. Partition key determines assignment.</p><p><strong>Delivery:</strong> At-least-once (consumer acknowledges after processing). Exactly-once with idempotent consumers.</p><p><strong>Retention:</strong> Time-based or size-based. Enables replay from any offset.</p>", rank: 36, difficulty: "medium", tags: ["message-queue", "kafka", "pub-sub"], premium: false },
    { slug: "design-recommendation-engine", question: "Design a recommendation engine.", short: "Collaborative filtering, content-based filtering, and hybrid approaches with real-time serving.", detailed: "<p><strong>Collaborative filtering:</strong> Users who liked X also liked Y. Matrix factorization (SVD). Cold start problem.</p><p><strong>Content-based:</strong> Recommend items similar to what user liked. Feature extraction from item metadata.</p><p><strong>Hybrid:</strong> Combine both approaches. Deep learning models (embeddings). A/B testing for model evaluation.</p><p><strong>Serving:</strong> Pre-compute recommendations offline. Real-time re-ranking with context (time, device, location).</p>", rank: 37, difficulty: "hard", tags: ["recommendations", "ml", "collaborative-filtering"], premium: true },
    { slug: "design-consistent-hashing", question: "Explain consistent hashing and implement it.", short: "Hash ring with virtual nodes for even distribution. Only K/N keys remap when nodes change.", detailed: "<p><strong>Concept:</strong> Nodes and keys mapped to positions on a hash ring (0 to 2^32). Each key assigned to the next clockwise node.</p><p><strong>Adding/removing node:</strong> Only keys between the new/removed node and its predecessor need remapping. ~K/N keys affected.</p><p><strong>Virtual nodes:</strong> Each physical node maps to multiple positions on the ring. Improves distribution uniformity.</p><p><strong>Applications:</strong> Distributed caches, CDNs, database sharding, load balancing.</p>", rank: 38, difficulty: "medium", tags: ["consistent-hashing", "distributed-systems", "partitioning"], premium: false },
    { slug: "design-circuit-breaker", question: "Explain the circuit breaker pattern.", short: "Prevents cascading failures by stopping requests to failing services, with automatic recovery.", detailed: "<p><strong>States:</strong> Closed (normal) → Open (failures exceed threshold, stop requests) → Half-Open (allow test request to check recovery).</p><p><strong>Configuration:</strong> Failure threshold, timeout duration, half-open trial count.</p><p><strong>Benefits:</strong> Prevents cascading failures, gives failing service time to recover, provides fallback responses.</p><p><strong>Implementation:</strong> Libraries like Hystrix, Resilience4j, or custom with state machine.</p>", rank: 39, difficulty: "medium", tags: ["circuit-breaker", "resilience", "microservices"], premium: false },
    { slug: "design-service-discovery", question: "Explain service discovery in microservices.", short: "Registry-based (Consul, Eureka) or DNS-based discovery for dynamic service location.", detailed: "<p><strong>Client-side discovery:</strong> Client queries registry (Consul, Eureka), gets service addresses, load balances itself.</p><p><strong>Server-side discovery:</strong> Load balancer queries registry and routes requests. Client doesn't know about registry.</p><p><strong>DNS-based:</strong> Services register DNS records. Simple but slower to update (TTL caching).</p><p><strong>Health checks:</strong> Registry actively checks service health. Unhealthy instances removed from rotation.</p>", rank: 40, difficulty: "medium", tags: ["service-discovery", "microservices", "consul"], premium: false },
    { slug: "design-idempotent-api", question: "How do you design idempotent APIs?", short: "Idempotency keys, database constraints, and conditional operations ensure repeated requests produce the same result.", detailed: "<p><strong>Idempotency key:</strong> Client sends unique key with request. Server checks if key was processed before, returns cached response.</p><p><strong>Database level:</strong> Unique constraints, upsert operations, conditional updates (UPDATE WHERE version = X).</p><p><strong>HTTP methods:</strong> GET, PUT, DELETE are naturally idempotent. POST needs explicit idempotency handling.</p><p><strong>Storage:</strong> Store idempotency key → response mapping with TTL. Redis or database table.</p>", rank: 41, difficulty: "medium", tags: ["idempotency", "api-design", "reliability"], premium: false },
  ];
  sd.forEach(q => all.push(makeQ("system-design", q)));

  // ─── Behavioral (40 more) ─────────────────────────────────────────────
  const bh: Q[] = [
    { slug: "overcame-technical-challenge", question: "Tell me about a time you overcame a major technical challenge.", short: "Walk through the problem, your debugging/analysis approach, and the solution with measurable impact.", detailed: "<p>Structure: (1) The technical problem and its severity, (2) Your diagnostic approach, (3) Key insight that led to the solution, (4) Implementation and result, (5) What you learned about tackling hard problems.</p>", example: "<strong>S:</strong> Our API latency spiked to 5s during peak hours, causing timeouts.<br/><strong>T:</strong> I was tasked with diagnosing and fixing within 48 hours.<br/><strong>A:</strong> I profiled the hot path, found N+1 queries in the feed generator, replaced with batched lookups and Redis caching.<br/><strong>R:</strong> P99 latency dropped from 5s to 200ms.", rank: 11, difficulty: "medium", tags: ["technical", "debugging", "problem-solving"], premium: false },
    { slug: "took-ownership-outside-role", question: "Describe a time you took ownership of something outside your job description.", short: "Show initiative and willingness to go beyond defined responsibilities for team success.", detailed: "<p>This demonstrates ownership mindset. Cover: (1) What you noticed needed doing, (2) Why it wasn't anyone's explicit responsibility, (3) How you stepped up, (4) The impact of your initiative.</p>", rank: 12, difficulty: "easy", tags: ["ownership", "initiative", "proactive"], premium: false },
    { slug: "dealt-with-underperforming-teammate", question: "How did you handle a situation where a teammate was underperforming?", short: "Show empathy, direct communication, and supportive problem-solving rather than blame.", detailed: "<p>Steps: (1) Observe and gather specific examples, (2) Have a private, empathetic conversation, (3) Ask if they're facing challenges (personal or professional), (4) Offer concrete help (pair programming, workload adjustment), (5) Follow up on progress.</p>", rank: 13, difficulty: "hard", tags: ["leadership", "difficult-conversations", "empathy"], premium: true },
    { slug: "prioritized-competing-demands", question: "Tell me about a time you had to prioritize competing demands.", short: "Demonstrate a systematic framework for evaluating trade-offs and communicating decisions.", detailed: "<p>Cover: (1) The competing demands and stakeholders, (2) Your evaluation framework (impact, urgency, effort, dependencies), (3) How you communicated the trade-offs, (4) The decision and its outcome, (5) How you managed expectations for deprioritized items.</p>", rank: 14, difficulty: "medium", tags: ["prioritization", "decision-making", "stakeholders"], premium: false },
    { slug: "delivered-under-constraints", question: "Describe delivering a project with significant constraints.", short: "Show resourcefulness and creativity when facing limitations in time, budget, or resources.", detailed: "<p>Constraints could be: tight timeline, limited team, legacy system, budget cuts. Cover: (1) The constraints and their impact, (2) How you scoped the MVP, (3) Creative solutions or shortcuts (without cutting quality), (4) The outcome and what you delivered within constraints.</p>", rank: 15, difficulty: "medium", tags: ["constraints", "resourcefulness", "delivery"], premium: false },
    { slug: "disagreed-with-manager", question: "Tell me about a time you disagreed with your manager.", short: "Show respectful advocacy backed by data while ultimately supporting the final decision.", detailed: "<p>Key elements: (1) The disagreement and your reasoning, (2) How you presented your case with evidence, (3) How you listened to their perspective, (4) The resolution — did they change their mind, did you, or did you commit and execute despite disagreeing?</p>", rank: 16, difficulty: "hard", tags: ["disagreement", "advocacy", "professionalism"], premium: false },
    { slug: "learned-from-mistake-quickly", question: "Describe a time you had to learn something new very quickly.", short: "Demonstrate rapid learning ability and how you apply new knowledge under pressure.", detailed: "<p>Cover: (1) What you needed to learn and the time pressure, (2) Your accelerated learning strategy, (3) How you applied the knowledge, (4) The outcome and how the rapid learning benefited the team.</p>", rank: 17, difficulty: "easy", tags: ["learning", "adaptability", "pressure"], premium: false },
    { slug: "made-unpopular-decision", question: "Tell me about a time you made an unpopular decision.", short: "Show conviction, clear reasoning, and how you brought people along despite initial resistance.", detailed: "<p>Cover: (1) The decision and why it was unpopular, (2) Your reasoning and data behind it, (3) How you communicated and addressed concerns, (4) The outcome and whether people came around, (5) What you learned about decision-making and communication.</p>", rank: 18, difficulty: "hard", tags: ["decision-making", "courage", "communication"], premium: true },
    { slug: "built-something-from-scratch", question: "Describe building something from scratch — a system, process, or team.", short: "Show zero-to-one thinking: vision, planning, execution, and iteration.", detailed: "<p>Cover: (1) The gap or opportunity you identified, (2) Your vision and initial plan, (3) How you started (MVP approach), (4) Key decisions along the way, (5) How it evolved and its current impact.</p>", rank: 19, difficulty: "medium", tags: ["building", "zero-to-one", "initiative"], premium: false },
    { slug: "failed-to-meet-expectations", question: "Tell me about a time you failed to meet someone's expectations.", short: "Own the gap between expectations and delivery, explain the root cause, and describe corrective actions.", detailed: "<p>Cover: (1) What was expected and what you delivered, (2) The root cause of the gap, (3) How you communicated and took accountability, (4) What you did to recover, (5) Preventive measures you implemented.</p>", rank: 20, difficulty: "medium", tags: ["accountability", "failure", "recovery"], premium: false },
    { slug: "cross-team-collaboration", question: "Describe a successful cross-team collaboration.", short: "Show alignment skills, communication across boundaries, and delivering shared outcomes.", detailed: "<p>Cover: (1) The teams involved and the shared goal, (2) Challenges (different priorities, communication styles, timezones), (3) Your role in facilitating alignment, (4) How you maintained communication and tracked progress, (5) The outcome.</p>", rank: 21, difficulty: "medium", tags: ["collaboration", "cross-team", "communication"], premium: false },
    { slug: "simplified-complex-problem", question: "Tell me about a time you simplified a complex problem.", short: "Show analytical thinking and the ability to break down complexity into manageable parts.", detailed: "<p>Cover: (1) The complex problem and why it seemed overwhelming, (2) Your approach to decomposition, (3) How you identified the core issue vs. noise, (4) The simplified solution and its impact, (5) How simplification helped the team.</p>", rank: 22, difficulty: "medium", tags: ["simplification", "analysis", "problem-solving"], premium: false },
    { slug: "recovered-from-production-incident", question: "Describe how you handled a production incident.", short: "Show calm under pressure, systematic debugging, clear communication, and post-mortem learnings.", detailed: "<p>Cover: (1) The incident and its impact (users affected, severity), (2) Your immediate response and triage, (3) How you communicated with stakeholders, (4) The root cause and fix, (5) Post-mortem and preventive measures implemented.</p>", example: "<strong>S:</strong> Our payment service went down during Black Friday, blocking all checkouts.<br/><strong>T:</strong> As on-call engineer, I led the incident response.<br/><strong>A:</strong> Set up a war room, identified a connection pool exhaustion, deployed a hotfix with increased pool size and circuit breaker in 45 minutes.<br/><strong>R:</strong> Revenue impact limited to ~$50K vs. projected $500K/hr. Post-mortem led to automated scaling and load testing in CI.", rank: 23, difficulty: "hard", tags: ["incident-response", "debugging", "production"], premium: false },
    { slug: "gave-difficult-feedback", question: "Tell me about a time you had to give difficult feedback.", short: "Show empathy, directness, and focus on behavior/impact rather than personality.", detailed: "<p>Cover: (1) The situation and why feedback was needed, (2) How you prepared for the conversation, (3) Your delivery approach (specific, timely, focused on behavior and impact), (4) The person's reaction and how you handled it, (5) The outcome and relationship afterward.</p>", rank: 24, difficulty: "medium", tags: ["feedback", "difficult-conversations", "leadership"], premium: false },
    { slug: "championed-diversity", question: "Describe a time you championed diversity or inclusion.", short: "Show concrete actions you took to create more inclusive outcomes, not just awareness.", detailed: "<p>Cover: (1) The situation where D&I was lacking, (2) Your specific actions (not just opinions), (3) Any resistance you faced, (4) The measurable outcome (more diverse hiring, inclusive processes, better team dynamics).</p>", rank: 25, difficulty: "medium", tags: ["diversity", "inclusion", "culture"], premium: false },
    { slug: "data-driven-decision", question: "Tell me about a decision you made based on data.", short: "Demonstrate analytical thinking: hypothesis, data collection, analysis, and evidence-based conclusion.", detailed: "<p>Cover: (1) The decision to be made and competing options, (2) What data you gathered and how, (3) Your analysis approach, (4) The data-driven conclusion and its reception, (5) The outcome validating (or challenging) your analysis.</p>", rank: 26, difficulty: "medium", tags: ["data-driven", "analytics", "decision-making"], premium: false },
    { slug: "managed-competing-deadlines", question: "How did you manage when two important deadlines conflicted?", short: "Show time management, communication with stakeholders, and creative solutions.", detailed: "<p>Cover: (1) The two competing deadlines and their importance, (2) How you assessed priorities, (3) Communication with stakeholders about trade-offs, (4) Your execution strategy (delegation, scope reduction, parallel work), (5) How both were resolved.</p>", rank: 27, difficulty: "medium", tags: ["time-management", "deadlines", "prioritization"], premium: false },
    { slug: "motivated-demotivated-team", question: "Describe motivating a demoralized team.", short: "Show empathy, understand root causes, and take concrete actions to rebuild morale.", detailed: "<p>Cover: (1) Why the team was demoralized (failed project, layoffs, poor management), (2) How you assessed the situation (1:1s, listening), (3) Specific actions you took (celebrating small wins, removing blockers, advocating upward), (4) How morale improved over time.</p>", rank: 28, difficulty: "hard", tags: ["motivation", "leadership", "team-morale"], premium: true },
    { slug: "said-no-to-stakeholder", question: "Tell me about a time you had to say no to a stakeholder.", short: "Show how you pushed back respectfully while offering alternatives.", detailed: "<p>Cover: (1) The request and why it was problematic (scope, timeline, technical feasibility), (2) How you communicated the 'no' with empathy and data, (3) Alternatives you proposed, (4) The stakeholder's reaction and the outcome.</p>", rank: 29, difficulty: "medium", tags: ["stakeholder-management", "pushback", "communication"], premium: false },
    { slug: "coached-someone-through-struggle", question: "Describe coaching someone through a professional struggle.", short: "Show patience, empathy, and effective coaching techniques that led to growth.", detailed: "<p>Cover: (1) The person and their challenge, (2) Your coaching approach (asking questions vs. giving answers, providing resources, setting goals), (3) How you balanced support with accountability, (4) Their growth and the outcome.</p>", rank: 30, difficulty: "medium", tags: ["coaching", "mentorship", "development"], premium: false },
  ];
  bh.forEach(q => all.push(makeQ("behavioral", q)));

  // ─── Frontend Engineering (40 more) ───────────────────────────────────
  const fe: Q[] = [
    { slug: "react-state-management", question: "Compare React state management approaches.", short: "Local state, Context, Redux, Zustand, and server state tools (React Query/SWR) each solve different problems.", detailed: "<p><strong>Local state (useState):</strong> Component-scoped. Best for UI state (toggles, form inputs).</p><p><strong>Context:</strong> Prop-drilling solution. Best for theme, auth, locale. Poor for frequently changing state (causes re-renders).</p><p><strong>Redux/Zustand:</strong> Global state with fine-grained subscriptions. Best for complex client state shared across many components.</p><p><strong>React Query/SWR:</strong> Server state management. Caching, revalidation, optimistic updates. Best for data fetched from APIs.</p>", rank: 11, difficulty: "medium", tags: ["react", "state-management", "redux", "context"], premium: false },
    { slug: "debounce-vs-throttle", question: "Explain debounce vs. throttle with use cases.", short: "Debounce waits for inactivity; throttle limits execution rate. Both optimize performance for frequent events.", detailed: "<p><strong>Debounce:</strong> Delays execution until no new calls for N ms. Use for: search input (wait until user stops typing), window resize handler, auto-save.</p><p><strong>Throttle:</strong> Executes at most once per N ms. Use for: scroll handlers, rate-limited API calls, mousemove tracking.</p><p><strong>Implementation:</strong> Both use setTimeout. Debounce clears the timer on each call. Throttle ignores calls within the cooldown period.</p>", rank: 12, difficulty: "medium", tags: ["javascript", "debounce", "throttle", "performance"], premium: false },
    { slug: "cors-explained", question: "What is CORS and how does it work?", short: "Cross-Origin Resource Sharing is a browser security mechanism controlling which origins can access your API.", detailed: "<p><strong>Same-Origin Policy:</strong> Browsers block requests to different origins (protocol + domain + port) by default.</p><p><strong>CORS headers:</strong> Server responds with Access-Control-Allow-Origin, Access-Control-Allow-Methods, Access-Control-Allow-Headers.</p><p><strong>Preflight:</strong> For non-simple requests (PUT, DELETE, custom headers), browser sends OPTIONS request first. Server must respond with appropriate CORS headers.</p><p><strong>Credentials:</strong> Cookies/auth requires Access-Control-Allow-Credentials: true AND specific origin (not *).</p>", rank: 13, difficulty: "medium", tags: ["cors", "security", "http", "browser"], premium: false },
    { slug: "css-specificity", question: "How does CSS specificity work?", short: "Inline > ID > Class/Attribute/Pseudo-class > Element/Pseudo-element. More specific selectors override less specific ones.", detailed: "<p><strong>Specificity calculation (a,b,c,d):</strong></p><p><strong>a:</strong> Inline styles (1,0,0,0)<br/><strong>b:</strong> ID selectors (0,1,0,0)<br/><strong>c:</strong> Classes, attributes, pseudo-classes (0,0,1,0)<br/><strong>d:</strong> Elements, pseudo-elements (0,0,0,1)</p><p><strong>!important</strong> overrides all specificity (avoid when possible).</p><p><strong>Cascade order:</strong> Origin → Specificity → Source order. Later rules win at equal specificity.</p>", rank: 14, difficulty: "easy", tags: ["css", "specificity", "cascade", "fundamentals"], premium: false },
    { slug: "lazy-loading-techniques", question: "What are different lazy loading techniques for web apps?", short: "Route-based splitting, component lazy loading, image lazy loading, and intersection observer patterns.", detailed: "<p><strong>Route-based:</strong> Dynamic import() for route components. Only load code for the current page.</p><p><strong>Component:</strong> React.lazy() + Suspense. Load heavy components on demand (modals, charts).</p><p><strong>Images:</strong> loading='lazy' attribute. IntersectionObserver for custom implementations. Placeholder blur-up pattern.</p><p><strong>Libraries:</strong> Code split vendor bundles. Tree-shake unused exports. Analyze with webpack-bundle-analyzer.</p>", rank: 15, difficulty: "medium", tags: ["lazy-loading", "code-splitting", "performance"], premium: false },
    { slug: "typescript-generics", question: "Explain TypeScript generics with practical examples.", short: "Generics enable type-safe reusable code by parameterizing types instead of using 'any'.", detailed: "<p><strong>Basic:</strong> <code>function identity&lt;T&gt;(arg: T): T</code> — works with any type while preserving type info.</p><p><strong>Constraints:</strong> <code>&lt;T extends HasLength&gt;</code> — restrict T to types with specific properties.</p><p><strong>Common patterns:</strong> Generic components (<code>List&lt;Item&gt;</code>), utility types (<code>Partial&lt;T&gt;</code>, <code>Pick&lt;T, K&gt;</code>), generic API response wrappers.</p><p><strong>Why not 'any':</strong> Generics maintain type safety across the function. 'any' loses all type information.</p>", rank: 16, difficulty: "medium", tags: ["typescript", "generics", "type-safety"], premium: false },
    { slug: "web-security-xss-csrf", question: "Explain XSS and CSRF attacks and their prevention.", short: "XSS: injecting malicious scripts. CSRF: tricking authenticated users into unwanted actions. Both preventable with proper measures.", detailed: "<p><strong>XSS (Cross-Site Scripting):</strong> Attacker injects malicious JavaScript. Types: Stored, Reflected, DOM-based. Prevention: sanitize output, CSP headers, HttpOnly cookies, avoid innerHTML.</p><p><strong>CSRF (Cross-Site Request Forgery):</strong> Attacker tricks user's browser into making authenticated requests. Prevention: CSRF tokens, SameSite cookies, check Referer/Origin headers, require re-authentication for sensitive actions.</p>", rank: 17, difficulty: "hard", tags: ["security", "xss", "csrf", "web-security"], premium: false },
    { slug: "react-rendering-optimization", question: "How do you optimize React rendering performance?", short: "React.memo, useMemo, useCallback, virtualization, code splitting, and avoiding unnecessary re-renders.", detailed: "<p><strong>Prevent unnecessary re-renders:</strong> React.memo for pure components. useMemo for expensive computations. useCallback for stable function references.</p><p><strong>State management:</strong> Keep state close to where it's used. Split context to avoid broad re-renders.</p><p><strong>Virtualization:</strong> react-window/react-virtuoso for long lists. Only render visible items.</p><p><strong>Profiling:</strong> React DevTools Profiler to identify bottlenecks. Why Did You Render library.</p>", rank: 18, difficulty: "hard", tags: ["react", "performance", "optimization", "memoization"], premium: true },
    { slug: "service-workers-explained", question: "What are Service Workers and their use cases?", short: "Background scripts enabling offline support, push notifications, and background sync.", detailed: "<p>Service Workers are JavaScript workers that run in a separate thread, intercepting network requests.</p><p><strong>Use cases:</strong> (1) Offline support — cache assets and API responses, (2) Push notifications — receive and display notifications, (3) Background sync — queue actions when offline, sync when online, (4) Performance — precache critical assets.</p><p><strong>Lifecycle:</strong> Register → Install (cache assets) → Activate (cleanup old caches) → Fetch (intercept requests).</p>", rank: 19, difficulty: "hard", tags: ["service-workers", "pwa", "offline", "caching"], premium: true },
    { slug: "responsive-design-approaches", question: "What are modern approaches to responsive design?", short: "Mobile-first CSS, fluid typography, container queries, and responsive images.", detailed: "<p><strong>Mobile-first:</strong> Base styles for mobile, add complexity with min-width media queries.</p><p><strong>Fluid typography:</strong> clamp() for fluid font sizes. Viewport units with min/max bounds.</p><p><strong>Container queries:</strong> @container — style based on parent size, not viewport. More composable than media queries.</p><p><strong>Responsive images:</strong> srcset for resolution switching. &lt;picture&gt; for art direction. lazy loading for off-screen images.</p><p><strong>Layout:</strong> CSS Grid auto-fit/auto-fill for adaptive grids. Flexbox wrap for flow layouts.</p>", rank: 20, difficulty: "medium", tags: ["responsive", "css", "mobile-first", "container-queries"], premium: false },
    { slug: "next-js-rendering-strategies", question: "Compare Next.js rendering strategies: SSR, SSG, ISR, and CSR.", short: "Each strategy optimizes for different trade-offs between freshness, performance, and SEO.", detailed: "<p><strong>SSR (Server-Side Rendering):</strong> Page rendered on each request. Fresh data, good SEO, but slower TTFB.</p><p><strong>SSG (Static Site Generation):</strong> Page rendered at build time. Fastest TTFB, great SEO, but stale data until rebuild.</p><p><strong>ISR (Incremental Static Regeneration):</strong> Static pages that revalidate in background after a timeout. Best of both worlds.</p><p><strong>CSR (Client-Side Rendering):</strong> JavaScript renders in browser. Fast navigation, poor initial SEO, loading spinners.</p><p><strong>App Router:</strong> Server Components (default) + Client Components ('use client'). Streaming SSR with Suspense boundaries.</p>", rank: 21, difficulty: "medium", tags: ["nextjs", "ssr", "ssg", "isr", "rendering"], premium: false },
    { slug: "testing-frontend-applications", question: "How do you approach testing frontend applications?", short: "Testing pyramid: unit tests for logic, integration tests for components, E2E tests for critical flows.", detailed: "<p><strong>Unit tests:</strong> Pure functions, hooks, utilities. Jest/Vitest. Fast, many of these.</p><p><strong>Component tests:</strong> Render components, simulate interactions, assert output. React Testing Library. Focus on user behavior, not implementation.</p><p><strong>Integration tests:</strong> Multiple components working together. Mock API calls with MSW.</p><p><strong>E2E tests:</strong> Full browser tests for critical user flows. Playwright/Cypress. Slower, fewer of these.</p><p><strong>Principle:</strong> Test behavior, not implementation. Don't test framework internals.</p>", rank: 22, difficulty: "medium", tags: ["testing", "jest", "react-testing-library", "e2e"], premium: false },
    { slug: "web-vitals-explained", question: "Explain Core Web Vitals and how to improve them.", short: "LCP (loading), INP (interactivity), CLS (visual stability) — Google's key UX metrics.", detailed: "<p><strong>LCP (Largest Contentful Paint):</strong> Time to render largest visible element. Target: <2.5s. Improve: optimize images, preload fonts, reduce server response time.</p><p><strong>INP (Interaction to Next Paint):</strong> Responsiveness to user input. Target: <200ms. Improve: break long tasks, use web workers, debounce handlers.</p><p><strong>CLS (Cumulative Layout Shift):</strong> Visual stability score. Target: <0.1. Improve: set image dimensions, reserve space for ads/embeds, avoid injecting content above fold.</p>", rank: 23, difficulty: "hard", tags: ["web-vitals", "performance", "lcp", "cls"], premium: false },
    { slug: "javascript-event-loop", question: "Explain the JavaScript event loop.", short: "Single-threaded execution with a call stack, task queue, and microtask queue for async operations.", detailed: "<p><strong>Call Stack:</strong> Synchronous code executes here. One function at a time (single-threaded).</p><p><strong>Web APIs:</strong> Browser handles setTimeout, fetch, DOM events in background threads.</p><p><strong>Task Queue (Macrotasks):</strong> setTimeout, setInterval, I/O callbacks. Processed one per loop iteration.</p><p><strong>Microtask Queue:</strong> Promise callbacks, queueMicrotask, MutationObserver. ALL microtasks processed before next macrotask.</p><p><strong>Order:</strong> Call stack → All microtasks → One macrotask → Render → Repeat.</p>", rank: 24, difficulty: "medium", tags: ["javascript", "event-loop", "async", "fundamentals"], premium: false },
    { slug: "progressive-web-apps", question: "What makes a Progressive Web App (PWA)?", short: "Installable, offline-capable, fast web applications using service workers, manifest, and HTTPS.", detailed: "<p><strong>Requirements:</strong> (1) HTTPS, (2) Web App Manifest (name, icons, start URL, display mode), (3) Service Worker (offline support).</p><p><strong>Capabilities:</strong> Install to home screen, offline functionality, push notifications, background sync, share target.</p><p><strong>Benefits:</strong> Cross-platform, no app store, automatic updates, smaller than native apps, deep linkable.</p><p><strong>Limitations:</strong> Limited access to native APIs (improving with Project Fugu), iOS Safari restrictions.</p>", rank: 25, difficulty: "medium", tags: ["pwa", "service-workers", "manifest", "offline"], premium: false },
  ];
  fe.forEach(q => all.push(makeQ("frontend", q)));

  // ─── Technical Core CS (30 more) ──────────────────────────────────────
  const tc: Q[] = [
    { slug: "trie-data-structure", question: "Explain the Trie data structure and its applications.", short: "A tree-like structure for storing strings where each node represents a character prefix.", detailed: "<p>A Trie (prefix tree) stores strings character by character. Each path from root to a marked node represents a stored string.</p><p><strong>Operations:</strong> Insert O(m), Search O(m), Prefix search O(m) — where m is string length.</p><p><strong>Space:</strong> Can be memory-intensive. Compressed Tries (Radix Trees) reduce space.</p><p><strong>Applications:</strong> Autocomplete, spell checkers, IP routing, dictionary implementations, DNA sequence matching.</p>", rank: 21, difficulty: "medium", tags: ["trie", "prefix-tree", "data-structures"], premium: false },
    { slug: "topological-sort", question: "Explain topological sorting and its applications.", short: "Linear ordering of vertices in a DAG such that for every edge (u,v), u comes before v.", detailed: "<p>Only works on Directed Acyclic Graphs (DAGs). Two algorithms:</p><p><strong>Kahn's Algorithm (BFS):</strong> Start with nodes having no incoming edges. Remove them, reduce in-degree of neighbors. Repeat.</p><p><strong>DFS-based:</strong> Run DFS, add node to result stack when all descendants are visited. Reverse stack = topological order.</p><p><strong>Applications:</strong> Build systems (Makefile), task scheduling, course prerequisites, package dependency resolution.</p>", rank: 22, difficulty: "hard", tags: ["topological-sort", "graphs", "dag", "algorithms"], premium: true },
    { slug: "design-patterns-overview", question: "Describe common software design patterns.", short: "Creational (Factory, Singleton), Structural (Adapter, Decorator), Behavioral (Observer, Strategy) patterns.", detailed: "<p><strong>Creational:</strong> Factory (create objects without specifying class), Singleton (one instance), Builder (step-by-step construction).</p><p><strong>Structural:</strong> Adapter (incompatible interface bridge), Decorator (add behavior dynamically), Facade (simplified interface).</p><p><strong>Behavioral:</strong> Observer (pub/sub), Strategy (interchangeable algorithms), Command (encapsulate actions).</p><p><strong>Modern additions:</strong> Repository, Dependency Injection, Circuit Breaker, CQRS.</p>", rank: 23, difficulty: "medium", tags: ["design-patterns", "oop", "architecture"], premium: false },
    { slug: "solid-principles", question: "Explain the SOLID principles.", short: "Five design principles for maintainable, flexible object-oriented code.", detailed: "<p><strong>S — Single Responsibility:</strong> A class should have one reason to change.</p><p><strong>O — Open/Closed:</strong> Open for extension, closed for modification.</p><p><strong>L — Liskov Substitution:</strong> Subtypes must be substitutable for base types.</p><p><strong>I — Interface Segregation:</strong> Prefer small, specific interfaces over large, general ones.</p><p><strong>D — Dependency Inversion:</strong> Depend on abstractions, not concrete implementations.</p>", rank: 24, difficulty: "medium", tags: ["solid", "oop", "principles", "architecture"], premium: false },
    { slug: "concurrency-vs-parallelism", question: "What's the difference between concurrency and parallelism?", short: "Concurrency: managing multiple tasks (interleaving). Parallelism: executing multiple tasks simultaneously.", detailed: "<p><strong>Concurrency:</strong> Dealing with multiple things at once. Tasks can make progress in overlapping time periods. Single core can be concurrent (context switching).</p><p><strong>Parallelism:</strong> Doing multiple things at once. Requires multiple cores/processors. Subset of concurrency.</p><p><strong>Analogy:</strong> Concurrency = one chef managing multiple dishes. Parallelism = multiple chefs each cooking a dish.</p><p><strong>Go:</strong> Goroutines for concurrency. GOMAXPROCS for parallelism.</p>", rank: 25, difficulty: "medium", tags: ["concurrency", "parallelism", "os", "fundamentals"], premium: false },
    { slug: "http2-vs-http3", question: "Compare HTTP/2 and HTTP/3.", short: "HTTP/2: multiplexing over TCP. HTTP/3: QUIC protocol over UDP for faster, more reliable connections.", detailed: "<p><strong>HTTP/2:</strong> Multiplexed streams over single TCP connection. Header compression (HPACK). Server push. Binary framing. Problem: TCP head-of-line blocking.</p><p><strong>HTTP/3:</strong> Built on QUIC (UDP-based). Independent streams (no HOL blocking). Faster connection setup (0-RTT). Built-in encryption. Better for mobile (connection migration).</p><p><strong>Migration:</strong> HTTP/3 is backward-compatible. Alt-Svc header for protocol negotiation.</p>", rank: 26, difficulty: "hard", tags: ["http", "protocols", "networking", "quic"], premium: true },
    { slug: "garbage-collection", question: "How does garbage collection work?", short: "Automatic memory management that reclaims memory from unreachable objects using tracing or reference counting.", detailed: "<p><strong>Reference Counting:</strong> Track references to each object. Free when count reaches 0. Problem: circular references.</p><p><strong>Mark-and-Sweep:</strong> Mark all reachable objects from roots, sweep (free) unmarked objects.</p><p><strong>Generational GC:</strong> Most objects die young. Separate heap into generations. Frequent minor GCs on young generation, rare major GCs on old generation.</p><p><strong>JS V8:</strong> Generational with Scavenge (young) and Mark-Compact (old). Incremental marking to reduce pauses.</p>", rank: 27, difficulty: "hard", tags: ["garbage-collection", "memory", "runtime"], premium: false },
    { slug: "dns-resolution-process", question: "Explain the DNS resolution process.", short: "Browser cache → OS cache → Recursive resolver → Root → TLD → Authoritative nameserver.", detailed: "<p><strong>Steps:</strong> (1) Browser cache check, (2) OS resolver cache, (3) Query recursive resolver (ISP's DNS), (4) Root nameserver → referral to TLD (.com), (5) TLD nameserver → referral to authoritative NS, (6) Authoritative NS returns IP address.</p><p><strong>Records:</strong> A (IPv4), AAAA (IPv6), CNAME (alias), MX (mail), NS (nameserver), TXT (verification).</p><p><strong>Caching:</strong> TTL-based caching at each level. CDNs use low TTLs for faster failover.</p>", rank: 28, difficulty: "medium", tags: ["dns", "networking", "resolution"], premium: false },
    { slug: "oauth2-explained", question: "Explain OAuth 2.0 and its flows.", short: "Delegated authorization framework with flows for web apps, SPAs, mobile, and machine-to-machine.", detailed: "<p><strong>Core concept:</strong> User grants limited access to their resources on one service to another service, without sharing credentials.</p><p><strong>Authorization Code Flow:</strong> Server-side apps. Redirect to auth server → user consents → auth code → exchange for tokens. Most secure.</p><p><strong>PKCE Flow:</strong> SPAs and mobile. Authorization Code + code verifier/challenge. Prevents interception.</p><p><strong>Client Credentials:</strong> Machine-to-machine. No user involved. Service authenticates directly.</p>", rank: 29, difficulty: "medium", tags: ["oauth", "authentication", "security"], premium: false },
    { slug: "bloom-filter", question: "What is a Bloom filter and when would you use one?", short: "Probabilistic data structure for fast set membership testing — no false negatives, possible false positives.", detailed: "<p>A Bloom filter uses a bit array and multiple hash functions. Insert: hash item k times, set those bits. Query: hash item k times, check if all bits are set.</p><p><strong>Properties:</strong> Space-efficient. No false negatives (if says 'not in set', definitely not). Possible false positives (if says 'in set', might not be). Cannot delete.</p><p><strong>Use cases:</strong> Spam filtering, cache miss avoidance, database query optimization, distributed systems membership.</p>", rank: 30, difficulty: "hard", tags: ["bloom-filter", "probabilistic", "data-structures"], premium: true },
    { slug: "binary-search-variations", question: "Describe variations of binary search.", short: "Find first/last occurrence, search rotated array, find peak element, and search in 2D matrix.", detailed: "<p><strong>Standard:</strong> Find target in sorted array. O(log n).</p><p><strong>Lower/Upper bound:</strong> Find first/last occurrence of target. Adjust mid comparison to continue searching.</p><p><strong>Rotated array:</strong> Determine which half is sorted, then decide which half to search.</p><p><strong>Peak element:</strong> If mid > mid+1, peak is left. Otherwise peak is right.</p><p><strong>2D matrix:</strong> Treat as 1D array with index mapping: row = mid/cols, col = mid%cols.</p>", rank: 31, difficulty: "medium", tags: ["binary-search", "algorithms", "variations"], premium: false },
    { slug: "graph-representation", question: "Compare adjacency matrix vs. adjacency list for graphs.", short: "Matrix: O(1) edge lookup, O(V²) space. List: O(V+E) space, better for sparse graphs.", detailed: "<p><strong>Adjacency Matrix:</strong> V×V boolean/weight matrix. O(1) edge check. O(V²) space. Good for dense graphs. Easy to implement.</p><p><strong>Adjacency List:</strong> Array of linked lists/arrays. O(degree) edge check. O(V+E) space. Good for sparse graphs. More memory efficient for most real-world graphs.</p><p><strong>Choice:</strong> Most real-world graphs are sparse → adjacency list preferred. Dense graphs (social networks with communities) → matrix might be better for specific operations.</p>", rank: 32, difficulty: "easy", tags: ["graphs", "representation", "data-structures"], premium: false },
  ];
  tc.forEach(q => all.push(makeQ("technical-core", q)));

  return all;
}

async function seedBatch2() {
  console.log("🌱 Phase 6 — Batch 2 Content Seeding");
  console.log("=====================================\n");

  await mongoose.connect(MONGODB_URI!);
  console.log("[DB] Connected\n");

  const allCats = await Category.find({});
  const slugToId: Record<string, string> = {};
  for (const cat of allCats) { slugToId[cat.slug] = cat._id.toString(); }

  const questions = batch2Questions();
  console.log(`📝 Seeding ${questions.length} additional questions...`);

  let created = 0, skipped = 0;
  for (const q of questions) {
    const categoryId = slugToId[q.categorySlug];
    if (!categoryId) { console.error(`  ❌ Missing category: ${q.categorySlug}`); skipped++; continue; }
    const exists = await Question.findOne({ slug: q.slug });
    if (exists) { skipped++; continue; }
    await Question.create({ category: categoryId, slug: q.slug, question: q.question, answer: q.answer, videos: [], difficulty: q.difficulty, frequencyRank: q.frequencyRank, tags: q.tags, isPremium: q.isPremium, isPublished: true });
    created++;
  }

  console.log(`  ✚ Created: ${created}`);
  console.log(`  ⏭ Skipped: ${skipped}\n`);

  console.log("📊 Updating category question counts...");
  for (const cat of allCats) {
    const count = await Question.countDocuments({ category: cat._id, isPublished: true });
    await Category.updateOne({ _id: cat._id }, { $set: { questionCount: count } });
    console.log(`  ${cat.name}: ${count} questions`);
  }

  console.log("\n✅ Batch 2 complete!");
  await mongoose.disconnect();
  process.exit(0);
}

seedBatch2().catch(err => { console.error("❌", err); process.exit(1); });
